
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Pause` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Pause
 * 
 */
export type PauseModel = runtime.Types.Result.DefaultSelection<Prisma.$PausePayload>

export type AggregatePause = {
  _count: PauseCountAggregateOutputType | null
  _avg: PauseAvgAggregateOutputType | null
  _sum: PauseSumAggregateOutputType | null
  _min: PauseMinAggregateOutputType | null
  _max: PauseMaxAggregateOutputType | null
}

export type PauseAvgAggregateOutputType = {
  durationSeconds: number | null
}

export type PauseSumAggregateOutputType = {
  durationSeconds: number | null
}

export type PauseMinAggregateOutputType = {
  id: string | null
  pointSessionId: string | null
  status: $Enums.PauseStatus | null
  startedAt: Date | null
  endedAt: Date | null
  durationSeconds: number | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PauseMaxAggregateOutputType = {
  id: string | null
  pointSessionId: string | null
  status: $Enums.PauseStatus | null
  startedAt: Date | null
  endedAt: Date | null
  durationSeconds: number | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PauseCountAggregateOutputType = {
  id: number
  pointSessionId: number
  status: number
  startedAt: number
  endedAt: number
  durationSeconds: number
  reason: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PauseAvgAggregateInputType = {
  durationSeconds?: true
}

export type PauseSumAggregateInputType = {
  durationSeconds?: true
}

export type PauseMinAggregateInputType = {
  id?: true
  pointSessionId?: true
  status?: true
  startedAt?: true
  endedAt?: true
  durationSeconds?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type PauseMaxAggregateInputType = {
  id?: true
  pointSessionId?: true
  status?: true
  startedAt?: true
  endedAt?: true
  durationSeconds?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type PauseCountAggregateInputType = {
  id?: true
  pointSessionId?: true
  status?: true
  startedAt?: true
  endedAt?: true
  durationSeconds?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PauseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pause to aggregate.
   */
  where?: Prisma.PauseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pauses to fetch.
   */
  orderBy?: Prisma.PauseOrderByWithRelationInput | Prisma.PauseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PauseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pauses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pauses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Pauses
  **/
  _count?: true | PauseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PauseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PauseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PauseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PauseMaxAggregateInputType
}

export type GetPauseAggregateType<T extends PauseAggregateArgs> = {
      [P in keyof T & keyof AggregatePause]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePause[P]>
    : Prisma.GetScalarType<T[P], AggregatePause[P]>
}




export type PauseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PauseWhereInput
  orderBy?: Prisma.PauseOrderByWithAggregationInput | Prisma.PauseOrderByWithAggregationInput[]
  by: Prisma.PauseScalarFieldEnum[] | Prisma.PauseScalarFieldEnum
  having?: Prisma.PauseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PauseCountAggregateInputType | true
  _avg?: PauseAvgAggregateInputType
  _sum?: PauseSumAggregateInputType
  _min?: PauseMinAggregateInputType
  _max?: PauseMaxAggregateInputType
}

export type PauseGroupByOutputType = {
  id: string
  pointSessionId: string
  status: $Enums.PauseStatus
  startedAt: Date
  endedAt: Date | null
  durationSeconds: number | null
  reason: string | null
  createdAt: Date
  updatedAt: Date
  _count: PauseCountAggregateOutputType | null
  _avg: PauseAvgAggregateOutputType | null
  _sum: PauseSumAggregateOutputType | null
  _min: PauseMinAggregateOutputType | null
  _max: PauseMaxAggregateOutputType | null
}

export type GetPauseGroupByPayload<T extends PauseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PauseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PauseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PauseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PauseGroupByOutputType[P]>
      }
    >
  >



export type PauseWhereInput = {
  AND?: Prisma.PauseWhereInput | Prisma.PauseWhereInput[]
  OR?: Prisma.PauseWhereInput[]
  NOT?: Prisma.PauseWhereInput | Prisma.PauseWhereInput[]
  id?: Prisma.StringFilter<"Pause"> | string
  pointSessionId?: Prisma.StringFilter<"Pause"> | string
  status?: Prisma.EnumPauseStatusFilter<"Pause"> | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFilter<"Pause"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"Pause"> | Date | string | null
  durationSeconds?: Prisma.IntNullableFilter<"Pause"> | number | null
  reason?: Prisma.StringNullableFilter<"Pause"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Pause"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Pause"> | Date | string
  pointSession?: Prisma.XOR<Prisma.PointSessionScalarRelationFilter, Prisma.PointSessionWhereInput>
}

export type PauseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pointSessionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  durationSeconds?: Prisma.SortOrderInput | Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  pointSession?: Prisma.PointSessionOrderByWithRelationInput
}

export type PauseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PauseWhereInput | Prisma.PauseWhereInput[]
  OR?: Prisma.PauseWhereInput[]
  NOT?: Prisma.PauseWhereInput | Prisma.PauseWhereInput[]
  pointSessionId?: Prisma.StringFilter<"Pause"> | string
  status?: Prisma.EnumPauseStatusFilter<"Pause"> | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFilter<"Pause"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"Pause"> | Date | string | null
  durationSeconds?: Prisma.IntNullableFilter<"Pause"> | number | null
  reason?: Prisma.StringNullableFilter<"Pause"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Pause"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Pause"> | Date | string
  pointSession?: Prisma.XOR<Prisma.PointSessionScalarRelationFilter, Prisma.PointSessionWhereInput>
}, "id">

export type PauseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pointSessionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  durationSeconds?: Prisma.SortOrderInput | Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PauseCountOrderByAggregateInput
  _avg?: Prisma.PauseAvgOrderByAggregateInput
  _max?: Prisma.PauseMaxOrderByAggregateInput
  _min?: Prisma.PauseMinOrderByAggregateInput
  _sum?: Prisma.PauseSumOrderByAggregateInput
}

export type PauseScalarWhereWithAggregatesInput = {
  AND?: Prisma.PauseScalarWhereWithAggregatesInput | Prisma.PauseScalarWhereWithAggregatesInput[]
  OR?: Prisma.PauseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PauseScalarWhereWithAggregatesInput | Prisma.PauseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Pause"> | string
  pointSessionId?: Prisma.StringWithAggregatesFilter<"Pause"> | string
  status?: Prisma.EnumPauseStatusWithAggregatesFilter<"Pause"> | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"Pause"> | Date | string
  endedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Pause"> | Date | string | null
  durationSeconds?: Prisma.IntNullableWithAggregatesFilter<"Pause"> | number | null
  reason?: Prisma.StringNullableWithAggregatesFilter<"Pause"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Pause"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Pause"> | Date | string
}

export type PauseCreateInput = {
  id?: string
  status?: $Enums.PauseStatus
  startedAt: Date | string
  endedAt?: Date | string | null
  durationSeconds?: number | null
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  pointSession: Prisma.PointSessionCreateNestedOneWithoutPausesInput
}

export type PauseUncheckedCreateInput = {
  id?: string
  pointSessionId: string
  status?: $Enums.PauseStatus
  startedAt: Date | string
  endedAt?: Date | string | null
  durationSeconds?: number | null
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PauseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPauseStatusFieldUpdateOperationsInput | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pointSession?: Prisma.PointSessionUpdateOneRequiredWithoutPausesNestedInput
}

export type PauseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pointSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPauseStatusFieldUpdateOperationsInput | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PauseCreateManyInput = {
  id?: string
  pointSessionId: string
  status?: $Enums.PauseStatus
  startedAt: Date | string
  endedAt?: Date | string | null
  durationSeconds?: number | null
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PauseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPauseStatusFieldUpdateOperationsInput | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PauseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pointSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPauseStatusFieldUpdateOperationsInput | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PauseListRelationFilter = {
  every?: Prisma.PauseWhereInput
  some?: Prisma.PauseWhereInput
  none?: Prisma.PauseWhereInput
}

export type PauseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PauseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pointSessionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PauseAvgOrderByAggregateInput = {
  durationSeconds?: Prisma.SortOrder
}

export type PauseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pointSessionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PauseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pointSessionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PauseSumOrderByAggregateInput = {
  durationSeconds?: Prisma.SortOrder
}

export type PauseCreateNestedManyWithoutPointSessionInput = {
  create?: Prisma.XOR<Prisma.PauseCreateWithoutPointSessionInput, Prisma.PauseUncheckedCreateWithoutPointSessionInput> | Prisma.PauseCreateWithoutPointSessionInput[] | Prisma.PauseUncheckedCreateWithoutPointSessionInput[]
  connectOrCreate?: Prisma.PauseCreateOrConnectWithoutPointSessionInput | Prisma.PauseCreateOrConnectWithoutPointSessionInput[]
  createMany?: Prisma.PauseCreateManyPointSessionInputEnvelope
  connect?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
}

export type PauseUncheckedCreateNestedManyWithoutPointSessionInput = {
  create?: Prisma.XOR<Prisma.PauseCreateWithoutPointSessionInput, Prisma.PauseUncheckedCreateWithoutPointSessionInput> | Prisma.PauseCreateWithoutPointSessionInput[] | Prisma.PauseUncheckedCreateWithoutPointSessionInput[]
  connectOrCreate?: Prisma.PauseCreateOrConnectWithoutPointSessionInput | Prisma.PauseCreateOrConnectWithoutPointSessionInput[]
  createMany?: Prisma.PauseCreateManyPointSessionInputEnvelope
  connect?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
}

export type PauseUpdateManyWithoutPointSessionNestedInput = {
  create?: Prisma.XOR<Prisma.PauseCreateWithoutPointSessionInput, Prisma.PauseUncheckedCreateWithoutPointSessionInput> | Prisma.PauseCreateWithoutPointSessionInput[] | Prisma.PauseUncheckedCreateWithoutPointSessionInput[]
  connectOrCreate?: Prisma.PauseCreateOrConnectWithoutPointSessionInput | Prisma.PauseCreateOrConnectWithoutPointSessionInput[]
  upsert?: Prisma.PauseUpsertWithWhereUniqueWithoutPointSessionInput | Prisma.PauseUpsertWithWhereUniqueWithoutPointSessionInput[]
  createMany?: Prisma.PauseCreateManyPointSessionInputEnvelope
  set?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
  disconnect?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
  delete?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
  connect?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
  update?: Prisma.PauseUpdateWithWhereUniqueWithoutPointSessionInput | Prisma.PauseUpdateWithWhereUniqueWithoutPointSessionInput[]
  updateMany?: Prisma.PauseUpdateManyWithWhereWithoutPointSessionInput | Prisma.PauseUpdateManyWithWhereWithoutPointSessionInput[]
  deleteMany?: Prisma.PauseScalarWhereInput | Prisma.PauseScalarWhereInput[]
}

export type PauseUncheckedUpdateManyWithoutPointSessionNestedInput = {
  create?: Prisma.XOR<Prisma.PauseCreateWithoutPointSessionInput, Prisma.PauseUncheckedCreateWithoutPointSessionInput> | Prisma.PauseCreateWithoutPointSessionInput[] | Prisma.PauseUncheckedCreateWithoutPointSessionInput[]
  connectOrCreate?: Prisma.PauseCreateOrConnectWithoutPointSessionInput | Prisma.PauseCreateOrConnectWithoutPointSessionInput[]
  upsert?: Prisma.PauseUpsertWithWhereUniqueWithoutPointSessionInput | Prisma.PauseUpsertWithWhereUniqueWithoutPointSessionInput[]
  createMany?: Prisma.PauseCreateManyPointSessionInputEnvelope
  set?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
  disconnect?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
  delete?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
  connect?: Prisma.PauseWhereUniqueInput | Prisma.PauseWhereUniqueInput[]
  update?: Prisma.PauseUpdateWithWhereUniqueWithoutPointSessionInput | Prisma.PauseUpdateWithWhereUniqueWithoutPointSessionInput[]
  updateMany?: Prisma.PauseUpdateManyWithWhereWithoutPointSessionInput | Prisma.PauseUpdateManyWithWhereWithoutPointSessionInput[]
  deleteMany?: Prisma.PauseScalarWhereInput | Prisma.PauseScalarWhereInput[]
}

export type EnumPauseStatusFieldUpdateOperationsInput = {
  set?: $Enums.PauseStatus
}

export type PauseCreateWithoutPointSessionInput = {
  id?: string
  status?: $Enums.PauseStatus
  startedAt: Date | string
  endedAt?: Date | string | null
  durationSeconds?: number | null
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PauseUncheckedCreateWithoutPointSessionInput = {
  id?: string
  status?: $Enums.PauseStatus
  startedAt: Date | string
  endedAt?: Date | string | null
  durationSeconds?: number | null
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PauseCreateOrConnectWithoutPointSessionInput = {
  where: Prisma.PauseWhereUniqueInput
  create: Prisma.XOR<Prisma.PauseCreateWithoutPointSessionInput, Prisma.PauseUncheckedCreateWithoutPointSessionInput>
}

export type PauseCreateManyPointSessionInputEnvelope = {
  data: Prisma.PauseCreateManyPointSessionInput | Prisma.PauseCreateManyPointSessionInput[]
  skipDuplicates?: boolean
}

export type PauseUpsertWithWhereUniqueWithoutPointSessionInput = {
  where: Prisma.PauseWhereUniqueInput
  update: Prisma.XOR<Prisma.PauseUpdateWithoutPointSessionInput, Prisma.PauseUncheckedUpdateWithoutPointSessionInput>
  create: Prisma.XOR<Prisma.PauseCreateWithoutPointSessionInput, Prisma.PauseUncheckedCreateWithoutPointSessionInput>
}

export type PauseUpdateWithWhereUniqueWithoutPointSessionInput = {
  where: Prisma.PauseWhereUniqueInput
  data: Prisma.XOR<Prisma.PauseUpdateWithoutPointSessionInput, Prisma.PauseUncheckedUpdateWithoutPointSessionInput>
}

export type PauseUpdateManyWithWhereWithoutPointSessionInput = {
  where: Prisma.PauseScalarWhereInput
  data: Prisma.XOR<Prisma.PauseUpdateManyMutationInput, Prisma.PauseUncheckedUpdateManyWithoutPointSessionInput>
}

export type PauseScalarWhereInput = {
  AND?: Prisma.PauseScalarWhereInput | Prisma.PauseScalarWhereInput[]
  OR?: Prisma.PauseScalarWhereInput[]
  NOT?: Prisma.PauseScalarWhereInput | Prisma.PauseScalarWhereInput[]
  id?: Prisma.StringFilter<"Pause"> | string
  pointSessionId?: Prisma.StringFilter<"Pause"> | string
  status?: Prisma.EnumPauseStatusFilter<"Pause"> | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFilter<"Pause"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"Pause"> | Date | string | null
  durationSeconds?: Prisma.IntNullableFilter<"Pause"> | number | null
  reason?: Prisma.StringNullableFilter<"Pause"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Pause"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Pause"> | Date | string
}

export type PauseCreateManyPointSessionInput = {
  id?: string
  status?: $Enums.PauseStatus
  startedAt: Date | string
  endedAt?: Date | string | null
  durationSeconds?: number | null
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PauseUpdateWithoutPointSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPauseStatusFieldUpdateOperationsInput | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PauseUncheckedUpdateWithoutPointSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPauseStatusFieldUpdateOperationsInput | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PauseUncheckedUpdateManyWithoutPointSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPauseStatusFieldUpdateOperationsInput | $Enums.PauseStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PauseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pointSessionId?: boolean
  status?: boolean
  startedAt?: boolean
  endedAt?: boolean
  durationSeconds?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pointSession?: boolean | Prisma.PointSessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pause"]>

export type PauseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pointSessionId?: boolean
  status?: boolean
  startedAt?: boolean
  endedAt?: boolean
  durationSeconds?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pointSession?: boolean | Prisma.PointSessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pause"]>

export type PauseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pointSessionId?: boolean
  status?: boolean
  startedAt?: boolean
  endedAt?: boolean
  durationSeconds?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pointSession?: boolean | Prisma.PointSessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pause"]>

export type PauseSelectScalar = {
  id?: boolean
  pointSessionId?: boolean
  status?: boolean
  startedAt?: boolean
  endedAt?: boolean
  durationSeconds?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PauseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pointSessionId" | "status" | "startedAt" | "endedAt" | "durationSeconds" | "reason" | "createdAt" | "updatedAt", ExtArgs["result"]["pause"]>
export type PauseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pointSession?: boolean | Prisma.PointSessionDefaultArgs<ExtArgs>
}
export type PauseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pointSession?: boolean | Prisma.PointSessionDefaultArgs<ExtArgs>
}
export type PauseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pointSession?: boolean | Prisma.PointSessionDefaultArgs<ExtArgs>
}

export type $PausePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Pause"
  objects: {
    pointSession: Prisma.$PointSessionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pointSessionId: string
    status: $Enums.PauseStatus
    startedAt: Date
    endedAt: Date | null
    durationSeconds: number | null
    reason: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pause"]>
  composites: {}
}

export type PauseGetPayload<S extends boolean | null | undefined | PauseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PausePayload, S>

export type PauseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PauseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PauseCountAggregateInputType | true
  }

export interface PauseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Pause'], meta: { name: 'Pause' } }
  /**
   * Find zero or one Pause that matches the filter.
   * @param {PauseFindUniqueArgs} args - Arguments to find a Pause
   * @example
   * // Get one Pause
   * const pause = await prisma.pause.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PauseFindUniqueArgs>(args: Prisma.SelectSubset<T, PauseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PauseClient<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Pause that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PauseFindUniqueOrThrowArgs} args - Arguments to find a Pause
   * @example
   * // Get one Pause
   * const pause = await prisma.pause.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PauseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PauseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PauseClient<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pause that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PauseFindFirstArgs} args - Arguments to find a Pause
   * @example
   * // Get one Pause
   * const pause = await prisma.pause.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PauseFindFirstArgs>(args?: Prisma.SelectSubset<T, PauseFindFirstArgs<ExtArgs>>): Prisma.Prisma__PauseClient<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pause that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PauseFindFirstOrThrowArgs} args - Arguments to find a Pause
   * @example
   * // Get one Pause
   * const pause = await prisma.pause.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PauseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PauseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PauseClient<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Pauses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PauseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Pauses
   * const pauses = await prisma.pause.findMany()
   * 
   * // Get first 10 Pauses
   * const pauses = await prisma.pause.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pauseWithIdOnly = await prisma.pause.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PauseFindManyArgs>(args?: Prisma.SelectSubset<T, PauseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Pause.
   * @param {PauseCreateArgs} args - Arguments to create a Pause.
   * @example
   * // Create one Pause
   * const Pause = await prisma.pause.create({
   *   data: {
   *     // ... data to create a Pause
   *   }
   * })
   * 
   */
  create<T extends PauseCreateArgs>(args: Prisma.SelectSubset<T, PauseCreateArgs<ExtArgs>>): Prisma.Prisma__PauseClient<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Pauses.
   * @param {PauseCreateManyArgs} args - Arguments to create many Pauses.
   * @example
   * // Create many Pauses
   * const pause = await prisma.pause.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PauseCreateManyArgs>(args?: Prisma.SelectSubset<T, PauseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Pauses and returns the data saved in the database.
   * @param {PauseCreateManyAndReturnArgs} args - Arguments to create many Pauses.
   * @example
   * // Create many Pauses
   * const pause = await prisma.pause.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Pauses and only return the `id`
   * const pauseWithIdOnly = await prisma.pause.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PauseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PauseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Pause.
   * @param {PauseDeleteArgs} args - Arguments to delete one Pause.
   * @example
   * // Delete one Pause
   * const Pause = await prisma.pause.delete({
   *   where: {
   *     // ... filter to delete one Pause
   *   }
   * })
   * 
   */
  delete<T extends PauseDeleteArgs>(args: Prisma.SelectSubset<T, PauseDeleteArgs<ExtArgs>>): Prisma.Prisma__PauseClient<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Pause.
   * @param {PauseUpdateArgs} args - Arguments to update one Pause.
   * @example
   * // Update one Pause
   * const pause = await prisma.pause.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PauseUpdateArgs>(args: Prisma.SelectSubset<T, PauseUpdateArgs<ExtArgs>>): Prisma.Prisma__PauseClient<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Pauses.
   * @param {PauseDeleteManyArgs} args - Arguments to filter Pauses to delete.
   * @example
   * // Delete a few Pauses
   * const { count } = await prisma.pause.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PauseDeleteManyArgs>(args?: Prisma.SelectSubset<T, PauseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pauses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PauseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Pauses
   * const pause = await prisma.pause.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PauseUpdateManyArgs>(args: Prisma.SelectSubset<T, PauseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pauses and returns the data updated in the database.
   * @param {PauseUpdateManyAndReturnArgs} args - Arguments to update many Pauses.
   * @example
   * // Update many Pauses
   * const pause = await prisma.pause.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Pauses and only return the `id`
   * const pauseWithIdOnly = await prisma.pause.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PauseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PauseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Pause.
   * @param {PauseUpsertArgs} args - Arguments to update or create a Pause.
   * @example
   * // Update or create a Pause
   * const pause = await prisma.pause.upsert({
   *   create: {
   *     // ... data to create a Pause
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Pause we want to update
   *   }
   * })
   */
  upsert<T extends PauseUpsertArgs>(args: Prisma.SelectSubset<T, PauseUpsertArgs<ExtArgs>>): Prisma.Prisma__PauseClient<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Pauses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PauseCountArgs} args - Arguments to filter Pauses to count.
   * @example
   * // Count the number of Pauses
   * const count = await prisma.pause.count({
   *   where: {
   *     // ... the filter for the Pauses we want to count
   *   }
   * })
  **/
  count<T extends PauseCountArgs>(
    args?: Prisma.Subset<T, PauseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PauseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Pause.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PauseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PauseAggregateArgs>(args: Prisma.Subset<T, PauseAggregateArgs>): Prisma.PrismaPromise<GetPauseAggregateType<T>>

  /**
   * Group by Pause.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PauseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PauseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PauseGroupByArgs['orderBy'] }
      : { orderBy?: PauseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PauseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPauseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Pause model
 */
readonly fields: PauseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Pause.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PauseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pointSession<T extends Prisma.PointSessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PointSessionDefaultArgs<ExtArgs>>): Prisma.Prisma__PointSessionClient<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Pause model
 */
export interface PauseFieldRefs {
  readonly id: Prisma.FieldRef<"Pause", 'String'>
  readonly pointSessionId: Prisma.FieldRef<"Pause", 'String'>
  readonly status: Prisma.FieldRef<"Pause", 'PauseStatus'>
  readonly startedAt: Prisma.FieldRef<"Pause", 'DateTime'>
  readonly endedAt: Prisma.FieldRef<"Pause", 'DateTime'>
  readonly durationSeconds: Prisma.FieldRef<"Pause", 'Int'>
  readonly reason: Prisma.FieldRef<"Pause", 'String'>
  readonly createdAt: Prisma.FieldRef<"Pause", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Pause", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Pause findUnique
 */
export type PauseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  /**
   * Filter, which Pause to fetch.
   */
  where: Prisma.PauseWhereUniqueInput
}

/**
 * Pause findUniqueOrThrow
 */
export type PauseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  /**
   * Filter, which Pause to fetch.
   */
  where: Prisma.PauseWhereUniqueInput
}

/**
 * Pause findFirst
 */
export type PauseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  /**
   * Filter, which Pause to fetch.
   */
  where?: Prisma.PauseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pauses to fetch.
   */
  orderBy?: Prisma.PauseOrderByWithRelationInput | Prisma.PauseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pauses.
   */
  cursor?: Prisma.PauseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pauses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pauses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pauses.
   */
  distinct?: Prisma.PauseScalarFieldEnum | Prisma.PauseScalarFieldEnum[]
}

/**
 * Pause findFirstOrThrow
 */
export type PauseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  /**
   * Filter, which Pause to fetch.
   */
  where?: Prisma.PauseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pauses to fetch.
   */
  orderBy?: Prisma.PauseOrderByWithRelationInput | Prisma.PauseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pauses.
   */
  cursor?: Prisma.PauseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pauses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pauses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pauses.
   */
  distinct?: Prisma.PauseScalarFieldEnum | Prisma.PauseScalarFieldEnum[]
}

/**
 * Pause findMany
 */
export type PauseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  /**
   * Filter, which Pauses to fetch.
   */
  where?: Prisma.PauseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pauses to fetch.
   */
  orderBy?: Prisma.PauseOrderByWithRelationInput | Prisma.PauseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Pauses.
   */
  cursor?: Prisma.PauseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pauses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pauses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pauses.
   */
  distinct?: Prisma.PauseScalarFieldEnum | Prisma.PauseScalarFieldEnum[]
}

/**
 * Pause create
 */
export type PauseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  /**
   * The data needed to create a Pause.
   */
  data: Prisma.XOR<Prisma.PauseCreateInput, Prisma.PauseUncheckedCreateInput>
}

/**
 * Pause createMany
 */
export type PauseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Pauses.
   */
  data: Prisma.PauseCreateManyInput | Prisma.PauseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Pause createManyAndReturn
 */
export type PauseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * The data used to create many Pauses.
   */
  data: Prisma.PauseCreateManyInput | Prisma.PauseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Pause update
 */
export type PauseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  /**
   * The data needed to update a Pause.
   */
  data: Prisma.XOR<Prisma.PauseUpdateInput, Prisma.PauseUncheckedUpdateInput>
  /**
   * Choose, which Pause to update.
   */
  where: Prisma.PauseWhereUniqueInput
}

/**
 * Pause updateMany
 */
export type PauseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Pauses.
   */
  data: Prisma.XOR<Prisma.PauseUpdateManyMutationInput, Prisma.PauseUncheckedUpdateManyInput>
  /**
   * Filter which Pauses to update
   */
  where?: Prisma.PauseWhereInput
  /**
   * Limit how many Pauses to update.
   */
  limit?: number
}

/**
 * Pause updateManyAndReturn
 */
export type PauseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * The data used to update Pauses.
   */
  data: Prisma.XOR<Prisma.PauseUpdateManyMutationInput, Prisma.PauseUncheckedUpdateManyInput>
  /**
   * Filter which Pauses to update
   */
  where?: Prisma.PauseWhereInput
  /**
   * Limit how many Pauses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Pause upsert
 */
export type PauseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  /**
   * The filter to search for the Pause to update in case it exists.
   */
  where: Prisma.PauseWhereUniqueInput
  /**
   * In case the Pause found by the `where` argument doesn't exist, create a new Pause with this data.
   */
  create: Prisma.XOR<Prisma.PauseCreateInput, Prisma.PauseUncheckedCreateInput>
  /**
   * In case the Pause was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PauseUpdateInput, Prisma.PauseUncheckedUpdateInput>
}

/**
 * Pause delete
 */
export type PauseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  /**
   * Filter which Pause to delete.
   */
  where: Prisma.PauseWhereUniqueInput
}

/**
 * Pause deleteMany
 */
export type PauseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pauses to delete
   */
  where?: Prisma.PauseWhereInput
  /**
   * Limit how many Pauses to delete.
   */
  limit?: number
}

/**
 * Pause without action
 */
export type PauseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
}
