
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServerLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ServerLink
 * 
 */
export type ServerLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$ServerLinkPayload>

export type AggregateServerLink = {
  _count: ServerLinkCountAggregateOutputType | null
  _avg: ServerLinkAvgAggregateOutputType | null
  _sum: ServerLinkSumAggregateOutputType | null
  _min: ServerLinkMinAggregateOutputType | null
  _max: ServerLinkMaxAggregateOutputType | null
}

export type ServerLinkAvgAggregateOutputType = {
  lastKnownMemberCount: number | null
}

export type ServerLinkSumAggregateOutputType = {
  lastKnownMemberCount: number | null
}

export type ServerLinkMinAggregateOutputType = {
  id: string | null
  guildId: string | null
  subscriptionId: string | null
  linkedByUserId: string | null
  lastKnownMemberCount: number | null
  memberCountCheckedAt: Date | null
  status: $Enums.ServerLinkStatus | null
  linkedAt: Date | null
  unlinkedAt: Date | null
}

export type ServerLinkMaxAggregateOutputType = {
  id: string | null
  guildId: string | null
  subscriptionId: string | null
  linkedByUserId: string | null
  lastKnownMemberCount: number | null
  memberCountCheckedAt: Date | null
  status: $Enums.ServerLinkStatus | null
  linkedAt: Date | null
  unlinkedAt: Date | null
}

export type ServerLinkCountAggregateOutputType = {
  id: number
  guildId: number
  subscriptionId: number
  linkedByUserId: number
  lastKnownMemberCount: number
  memberCountCheckedAt: number
  status: number
  linkedAt: number
  unlinkedAt: number
  _all: number
}


export type ServerLinkAvgAggregateInputType = {
  lastKnownMemberCount?: true
}

export type ServerLinkSumAggregateInputType = {
  lastKnownMemberCount?: true
}

export type ServerLinkMinAggregateInputType = {
  id?: true
  guildId?: true
  subscriptionId?: true
  linkedByUserId?: true
  lastKnownMemberCount?: true
  memberCountCheckedAt?: true
  status?: true
  linkedAt?: true
  unlinkedAt?: true
}

export type ServerLinkMaxAggregateInputType = {
  id?: true
  guildId?: true
  subscriptionId?: true
  linkedByUserId?: true
  lastKnownMemberCount?: true
  memberCountCheckedAt?: true
  status?: true
  linkedAt?: true
  unlinkedAt?: true
}

export type ServerLinkCountAggregateInputType = {
  id?: true
  guildId?: true
  subscriptionId?: true
  linkedByUserId?: true
  lastKnownMemberCount?: true
  memberCountCheckedAt?: true
  status?: true
  linkedAt?: true
  unlinkedAt?: true
  _all?: true
}

export type ServerLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServerLink to aggregate.
   */
  where?: Prisma.ServerLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServerLinks to fetch.
   */
  orderBy?: Prisma.ServerLinkOrderByWithRelationInput | Prisma.ServerLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServerLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServerLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServerLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServerLinks
  **/
  _count?: true | ServerLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ServerLinkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ServerLinkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServerLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServerLinkMaxAggregateInputType
}

export type GetServerLinkAggregateType<T extends ServerLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateServerLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServerLink[P]>
    : Prisma.GetScalarType<T[P], AggregateServerLink[P]>
}




export type ServerLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServerLinkWhereInput
  orderBy?: Prisma.ServerLinkOrderByWithAggregationInput | Prisma.ServerLinkOrderByWithAggregationInput[]
  by: Prisma.ServerLinkScalarFieldEnum[] | Prisma.ServerLinkScalarFieldEnum
  having?: Prisma.ServerLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServerLinkCountAggregateInputType | true
  _avg?: ServerLinkAvgAggregateInputType
  _sum?: ServerLinkSumAggregateInputType
  _min?: ServerLinkMinAggregateInputType
  _max?: ServerLinkMaxAggregateInputType
}

export type ServerLinkGroupByOutputType = {
  id: string
  guildId: string
  subscriptionId: string
  linkedByUserId: string
  lastKnownMemberCount: number
  memberCountCheckedAt: Date
  status: $Enums.ServerLinkStatus
  linkedAt: Date
  unlinkedAt: Date | null
  _count: ServerLinkCountAggregateOutputType | null
  _avg: ServerLinkAvgAggregateOutputType | null
  _sum: ServerLinkSumAggregateOutputType | null
  _min: ServerLinkMinAggregateOutputType | null
  _max: ServerLinkMaxAggregateOutputType | null
}

export type GetServerLinkGroupByPayload<T extends ServerLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServerLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServerLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServerLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServerLinkGroupByOutputType[P]>
      }
    >
  >



export type ServerLinkWhereInput = {
  AND?: Prisma.ServerLinkWhereInput | Prisma.ServerLinkWhereInput[]
  OR?: Prisma.ServerLinkWhereInput[]
  NOT?: Prisma.ServerLinkWhereInput | Prisma.ServerLinkWhereInput[]
  id?: Prisma.StringFilter<"ServerLink"> | string
  guildId?: Prisma.StringFilter<"ServerLink"> | string
  subscriptionId?: Prisma.StringFilter<"ServerLink"> | string
  linkedByUserId?: Prisma.StringFilter<"ServerLink"> | string
  lastKnownMemberCount?: Prisma.IntFilter<"ServerLink"> | number
  memberCountCheckedAt?: Prisma.DateTimeFilter<"ServerLink"> | Date | string
  status?: Prisma.EnumServerLinkStatusFilter<"ServerLink"> | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFilter<"ServerLink"> | Date | string
  unlinkedAt?: Prisma.DateTimeNullableFilter<"ServerLink"> | Date | string | null
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
}

export type ServerLinkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  linkedByUserId?: Prisma.SortOrder
  lastKnownMemberCount?: Prisma.SortOrder
  memberCountCheckedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  linkedAt?: Prisma.SortOrder
  unlinkedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  guild?: Prisma.GuildOrderByWithRelationInput
  subscription?: Prisma.SubscriptionOrderByWithRelationInput
}

export type ServerLinkWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ServerLinkWhereInput | Prisma.ServerLinkWhereInput[]
  OR?: Prisma.ServerLinkWhereInput[]
  NOT?: Prisma.ServerLinkWhereInput | Prisma.ServerLinkWhereInput[]
  guildId?: Prisma.StringFilter<"ServerLink"> | string
  subscriptionId?: Prisma.StringFilter<"ServerLink"> | string
  linkedByUserId?: Prisma.StringFilter<"ServerLink"> | string
  lastKnownMemberCount?: Prisma.IntFilter<"ServerLink"> | number
  memberCountCheckedAt?: Prisma.DateTimeFilter<"ServerLink"> | Date | string
  status?: Prisma.EnumServerLinkStatusFilter<"ServerLink"> | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFilter<"ServerLink"> | Date | string
  unlinkedAt?: Prisma.DateTimeNullableFilter<"ServerLink"> | Date | string | null
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
}, "id">

export type ServerLinkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  linkedByUserId?: Prisma.SortOrder
  lastKnownMemberCount?: Prisma.SortOrder
  memberCountCheckedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  linkedAt?: Prisma.SortOrder
  unlinkedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ServerLinkCountOrderByAggregateInput
  _avg?: Prisma.ServerLinkAvgOrderByAggregateInput
  _max?: Prisma.ServerLinkMaxOrderByAggregateInput
  _min?: Prisma.ServerLinkMinOrderByAggregateInput
  _sum?: Prisma.ServerLinkSumOrderByAggregateInput
}

export type ServerLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServerLinkScalarWhereWithAggregatesInput | Prisma.ServerLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServerLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServerLinkScalarWhereWithAggregatesInput | Prisma.ServerLinkScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ServerLink"> | string
  guildId?: Prisma.StringWithAggregatesFilter<"ServerLink"> | string
  subscriptionId?: Prisma.StringWithAggregatesFilter<"ServerLink"> | string
  linkedByUserId?: Prisma.StringWithAggregatesFilter<"ServerLink"> | string
  lastKnownMemberCount?: Prisma.IntWithAggregatesFilter<"ServerLink"> | number
  memberCountCheckedAt?: Prisma.DateTimeWithAggregatesFilter<"ServerLink"> | Date | string
  status?: Prisma.EnumServerLinkStatusWithAggregatesFilter<"ServerLink"> | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeWithAggregatesFilter<"ServerLink"> | Date | string
  unlinkedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ServerLink"> | Date | string | null
}

export type ServerLinkCreateInput = {
  id?: string
  linkedByUserId: string
  lastKnownMemberCount?: number
  memberCountCheckedAt?: Date | string
  status?: $Enums.ServerLinkStatus
  linkedAt?: Date | string
  unlinkedAt?: Date | string | null
  guild: Prisma.GuildCreateNestedOneWithoutLinksInput
  subscription: Prisma.SubscriptionCreateNestedOneWithoutLinksInput
}

export type ServerLinkUncheckedCreateInput = {
  id?: string
  guildId: string
  subscriptionId: string
  linkedByUserId: string
  lastKnownMemberCount?: number
  memberCountCheckedAt?: Date | string
  status?: $Enums.ServerLinkStatus
  linkedAt?: Date | string
  unlinkedAt?: Date | string | null
}

export type ServerLinkUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  guild?: Prisma.GuildUpdateOneRequiredWithoutLinksNestedInput
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutLinksNestedInput
}

export type ServerLinkUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServerLinkCreateManyInput = {
  id?: string
  guildId: string
  subscriptionId: string
  linkedByUserId: string
  lastKnownMemberCount?: number
  memberCountCheckedAt?: Date | string
  status?: $Enums.ServerLinkStatus
  linkedAt?: Date | string
  unlinkedAt?: Date | string | null
}

export type ServerLinkUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServerLinkUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServerLinkListRelationFilter = {
  every?: Prisma.ServerLinkWhereInput
  some?: Prisma.ServerLinkWhereInput
  none?: Prisma.ServerLinkWhereInput
}

export type ServerLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ServerLinkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  linkedByUserId?: Prisma.SortOrder
  lastKnownMemberCount?: Prisma.SortOrder
  memberCountCheckedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  linkedAt?: Prisma.SortOrder
  unlinkedAt?: Prisma.SortOrder
}

export type ServerLinkAvgOrderByAggregateInput = {
  lastKnownMemberCount?: Prisma.SortOrder
}

export type ServerLinkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  linkedByUserId?: Prisma.SortOrder
  lastKnownMemberCount?: Prisma.SortOrder
  memberCountCheckedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  linkedAt?: Prisma.SortOrder
  unlinkedAt?: Prisma.SortOrder
}

export type ServerLinkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  linkedByUserId?: Prisma.SortOrder
  lastKnownMemberCount?: Prisma.SortOrder
  memberCountCheckedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  linkedAt?: Prisma.SortOrder
  unlinkedAt?: Prisma.SortOrder
}

export type ServerLinkSumOrderByAggregateInput = {
  lastKnownMemberCount?: Prisma.SortOrder
}

export type ServerLinkCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.ServerLinkCreateWithoutGuildInput, Prisma.ServerLinkUncheckedCreateWithoutGuildInput> | Prisma.ServerLinkCreateWithoutGuildInput[] | Prisma.ServerLinkUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.ServerLinkCreateOrConnectWithoutGuildInput | Prisma.ServerLinkCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.ServerLinkCreateManyGuildInputEnvelope
  connect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
}

export type ServerLinkUncheckedCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.ServerLinkCreateWithoutGuildInput, Prisma.ServerLinkUncheckedCreateWithoutGuildInput> | Prisma.ServerLinkCreateWithoutGuildInput[] | Prisma.ServerLinkUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.ServerLinkCreateOrConnectWithoutGuildInput | Prisma.ServerLinkCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.ServerLinkCreateManyGuildInputEnvelope
  connect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
}

export type ServerLinkUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.ServerLinkCreateWithoutGuildInput, Prisma.ServerLinkUncheckedCreateWithoutGuildInput> | Prisma.ServerLinkCreateWithoutGuildInput[] | Prisma.ServerLinkUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.ServerLinkCreateOrConnectWithoutGuildInput | Prisma.ServerLinkCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.ServerLinkUpsertWithWhereUniqueWithoutGuildInput | Prisma.ServerLinkUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.ServerLinkCreateManyGuildInputEnvelope
  set?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  disconnect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  delete?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  connect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  update?: Prisma.ServerLinkUpdateWithWhereUniqueWithoutGuildInput | Prisma.ServerLinkUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.ServerLinkUpdateManyWithWhereWithoutGuildInput | Prisma.ServerLinkUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.ServerLinkScalarWhereInput | Prisma.ServerLinkScalarWhereInput[]
}

export type ServerLinkUncheckedUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.ServerLinkCreateWithoutGuildInput, Prisma.ServerLinkUncheckedCreateWithoutGuildInput> | Prisma.ServerLinkCreateWithoutGuildInput[] | Prisma.ServerLinkUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.ServerLinkCreateOrConnectWithoutGuildInput | Prisma.ServerLinkCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.ServerLinkUpsertWithWhereUniqueWithoutGuildInput | Prisma.ServerLinkUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.ServerLinkCreateManyGuildInputEnvelope
  set?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  disconnect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  delete?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  connect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  update?: Prisma.ServerLinkUpdateWithWhereUniqueWithoutGuildInput | Prisma.ServerLinkUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.ServerLinkUpdateManyWithWhereWithoutGuildInput | Prisma.ServerLinkUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.ServerLinkScalarWhereInput | Prisma.ServerLinkScalarWhereInput[]
}

export type EnumServerLinkStatusFieldUpdateOperationsInput = {
  set?: $Enums.ServerLinkStatus
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ServerLinkCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.ServerLinkCreateWithoutSubscriptionInput, Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput> | Prisma.ServerLinkCreateWithoutSubscriptionInput[] | Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.ServerLinkCreateOrConnectWithoutSubscriptionInput | Prisma.ServerLinkCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.ServerLinkCreateManySubscriptionInputEnvelope
  connect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
}

export type ServerLinkUncheckedCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.ServerLinkCreateWithoutSubscriptionInput, Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput> | Prisma.ServerLinkCreateWithoutSubscriptionInput[] | Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.ServerLinkCreateOrConnectWithoutSubscriptionInput | Prisma.ServerLinkCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.ServerLinkCreateManySubscriptionInputEnvelope
  connect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
}

export type ServerLinkUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.ServerLinkCreateWithoutSubscriptionInput, Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput> | Prisma.ServerLinkCreateWithoutSubscriptionInput[] | Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.ServerLinkCreateOrConnectWithoutSubscriptionInput | Prisma.ServerLinkCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.ServerLinkUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.ServerLinkUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.ServerLinkCreateManySubscriptionInputEnvelope
  set?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  disconnect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  delete?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  connect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  update?: Prisma.ServerLinkUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.ServerLinkUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.ServerLinkUpdateManyWithWhereWithoutSubscriptionInput | Prisma.ServerLinkUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.ServerLinkScalarWhereInput | Prisma.ServerLinkScalarWhereInput[]
}

export type ServerLinkUncheckedUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.ServerLinkCreateWithoutSubscriptionInput, Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput> | Prisma.ServerLinkCreateWithoutSubscriptionInput[] | Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.ServerLinkCreateOrConnectWithoutSubscriptionInput | Prisma.ServerLinkCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.ServerLinkUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.ServerLinkUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.ServerLinkCreateManySubscriptionInputEnvelope
  set?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  disconnect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  delete?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  connect?: Prisma.ServerLinkWhereUniqueInput | Prisma.ServerLinkWhereUniqueInput[]
  update?: Prisma.ServerLinkUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.ServerLinkUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.ServerLinkUpdateManyWithWhereWithoutSubscriptionInput | Prisma.ServerLinkUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.ServerLinkScalarWhereInput | Prisma.ServerLinkScalarWhereInput[]
}

export type ServerLinkCreateWithoutGuildInput = {
  id?: string
  linkedByUserId: string
  lastKnownMemberCount?: number
  memberCountCheckedAt?: Date | string
  status?: $Enums.ServerLinkStatus
  linkedAt?: Date | string
  unlinkedAt?: Date | string | null
  subscription: Prisma.SubscriptionCreateNestedOneWithoutLinksInput
}

export type ServerLinkUncheckedCreateWithoutGuildInput = {
  id?: string
  subscriptionId: string
  linkedByUserId: string
  lastKnownMemberCount?: number
  memberCountCheckedAt?: Date | string
  status?: $Enums.ServerLinkStatus
  linkedAt?: Date | string
  unlinkedAt?: Date | string | null
}

export type ServerLinkCreateOrConnectWithoutGuildInput = {
  where: Prisma.ServerLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.ServerLinkCreateWithoutGuildInput, Prisma.ServerLinkUncheckedCreateWithoutGuildInput>
}

export type ServerLinkCreateManyGuildInputEnvelope = {
  data: Prisma.ServerLinkCreateManyGuildInput | Prisma.ServerLinkCreateManyGuildInput[]
  skipDuplicates?: boolean
}

export type ServerLinkUpsertWithWhereUniqueWithoutGuildInput = {
  where: Prisma.ServerLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.ServerLinkUpdateWithoutGuildInput, Prisma.ServerLinkUncheckedUpdateWithoutGuildInput>
  create: Prisma.XOR<Prisma.ServerLinkCreateWithoutGuildInput, Prisma.ServerLinkUncheckedCreateWithoutGuildInput>
}

export type ServerLinkUpdateWithWhereUniqueWithoutGuildInput = {
  where: Prisma.ServerLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.ServerLinkUpdateWithoutGuildInput, Prisma.ServerLinkUncheckedUpdateWithoutGuildInput>
}

export type ServerLinkUpdateManyWithWhereWithoutGuildInput = {
  where: Prisma.ServerLinkScalarWhereInput
  data: Prisma.XOR<Prisma.ServerLinkUpdateManyMutationInput, Prisma.ServerLinkUncheckedUpdateManyWithoutGuildInput>
}

export type ServerLinkScalarWhereInput = {
  AND?: Prisma.ServerLinkScalarWhereInput | Prisma.ServerLinkScalarWhereInput[]
  OR?: Prisma.ServerLinkScalarWhereInput[]
  NOT?: Prisma.ServerLinkScalarWhereInput | Prisma.ServerLinkScalarWhereInput[]
  id?: Prisma.StringFilter<"ServerLink"> | string
  guildId?: Prisma.StringFilter<"ServerLink"> | string
  subscriptionId?: Prisma.StringFilter<"ServerLink"> | string
  linkedByUserId?: Prisma.StringFilter<"ServerLink"> | string
  lastKnownMemberCount?: Prisma.IntFilter<"ServerLink"> | number
  memberCountCheckedAt?: Prisma.DateTimeFilter<"ServerLink"> | Date | string
  status?: Prisma.EnumServerLinkStatusFilter<"ServerLink"> | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFilter<"ServerLink"> | Date | string
  unlinkedAt?: Prisma.DateTimeNullableFilter<"ServerLink"> | Date | string | null
}

export type ServerLinkCreateWithoutSubscriptionInput = {
  id?: string
  linkedByUserId: string
  lastKnownMemberCount?: number
  memberCountCheckedAt?: Date | string
  status?: $Enums.ServerLinkStatus
  linkedAt?: Date | string
  unlinkedAt?: Date | string | null
  guild: Prisma.GuildCreateNestedOneWithoutLinksInput
}

export type ServerLinkUncheckedCreateWithoutSubscriptionInput = {
  id?: string
  guildId: string
  linkedByUserId: string
  lastKnownMemberCount?: number
  memberCountCheckedAt?: Date | string
  status?: $Enums.ServerLinkStatus
  linkedAt?: Date | string
  unlinkedAt?: Date | string | null
}

export type ServerLinkCreateOrConnectWithoutSubscriptionInput = {
  where: Prisma.ServerLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.ServerLinkCreateWithoutSubscriptionInput, Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput>
}

export type ServerLinkCreateManySubscriptionInputEnvelope = {
  data: Prisma.ServerLinkCreateManySubscriptionInput | Prisma.ServerLinkCreateManySubscriptionInput[]
  skipDuplicates?: boolean
}

export type ServerLinkUpsertWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.ServerLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.ServerLinkUpdateWithoutSubscriptionInput, Prisma.ServerLinkUncheckedUpdateWithoutSubscriptionInput>
  create: Prisma.XOR<Prisma.ServerLinkCreateWithoutSubscriptionInput, Prisma.ServerLinkUncheckedCreateWithoutSubscriptionInput>
}

export type ServerLinkUpdateWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.ServerLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.ServerLinkUpdateWithoutSubscriptionInput, Prisma.ServerLinkUncheckedUpdateWithoutSubscriptionInput>
}

export type ServerLinkUpdateManyWithWhereWithoutSubscriptionInput = {
  where: Prisma.ServerLinkScalarWhereInput
  data: Prisma.XOR<Prisma.ServerLinkUpdateManyMutationInput, Prisma.ServerLinkUncheckedUpdateManyWithoutSubscriptionInput>
}

export type ServerLinkCreateManyGuildInput = {
  id?: string
  subscriptionId: string
  linkedByUserId: string
  lastKnownMemberCount?: number
  memberCountCheckedAt?: Date | string
  status?: $Enums.ServerLinkStatus
  linkedAt?: Date | string
  unlinkedAt?: Date | string | null
}

export type ServerLinkUpdateWithoutGuildInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutLinksNestedInput
}

export type ServerLinkUncheckedUpdateWithoutGuildInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServerLinkUncheckedUpdateManyWithoutGuildInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServerLinkCreateManySubscriptionInput = {
  id?: string
  guildId: string
  linkedByUserId: string
  lastKnownMemberCount?: number
  memberCountCheckedAt?: Date | string
  status?: $Enums.ServerLinkStatus
  linkedAt?: Date | string
  unlinkedAt?: Date | string | null
}

export type ServerLinkUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  guild?: Prisma.GuildUpdateOneRequiredWithoutLinksNestedInput
}

export type ServerLinkUncheckedUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServerLinkUncheckedUpdateManyWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  linkedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  lastKnownMemberCount?: Prisma.IntFieldUpdateOperationsInput | number
  memberCountCheckedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumServerLinkStatusFieldUpdateOperationsInput | $Enums.ServerLinkStatus
  linkedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unlinkedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type ServerLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  subscriptionId?: boolean
  linkedByUserId?: boolean
  lastKnownMemberCount?: boolean
  memberCountCheckedAt?: boolean
  status?: boolean
  linkedAt?: boolean
  unlinkedAt?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serverLink"]>

export type ServerLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  subscriptionId?: boolean
  linkedByUserId?: boolean
  lastKnownMemberCount?: boolean
  memberCountCheckedAt?: boolean
  status?: boolean
  linkedAt?: boolean
  unlinkedAt?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serverLink"]>

export type ServerLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  subscriptionId?: boolean
  linkedByUserId?: boolean
  lastKnownMemberCount?: boolean
  memberCountCheckedAt?: boolean
  status?: boolean
  linkedAt?: boolean
  unlinkedAt?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serverLink"]>

export type ServerLinkSelectScalar = {
  id?: boolean
  guildId?: boolean
  subscriptionId?: boolean
  linkedByUserId?: boolean
  lastKnownMemberCount?: boolean
  memberCountCheckedAt?: boolean
  status?: boolean
  linkedAt?: boolean
  unlinkedAt?: boolean
}

export type ServerLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guildId" | "subscriptionId" | "linkedByUserId" | "lastKnownMemberCount" | "memberCountCheckedAt" | "status" | "linkedAt" | "unlinkedAt", ExtArgs["result"]["serverLink"]>
export type ServerLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}
export type ServerLinkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}
export type ServerLinkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}

export type $ServerLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServerLink"
  objects: {
    guild: Prisma.$GuildPayload<ExtArgs>
    subscription: Prisma.$SubscriptionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    guildId: string
    subscriptionId: string
    linkedByUserId: string
    lastKnownMemberCount: number
    memberCountCheckedAt: Date
    status: $Enums.ServerLinkStatus
    linkedAt: Date
    unlinkedAt: Date | null
  }, ExtArgs["result"]["serverLink"]>
  composites: {}
}

export type ServerLinkGetPayload<S extends boolean | null | undefined | ServerLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload, S>

export type ServerLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServerLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServerLinkCountAggregateInputType | true
  }

export interface ServerLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServerLink'], meta: { name: 'ServerLink' } }
  /**
   * Find zero or one ServerLink that matches the filter.
   * @param {ServerLinkFindUniqueArgs} args - Arguments to find a ServerLink
   * @example
   * // Get one ServerLink
   * const serverLink = await prisma.serverLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServerLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, ServerLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServerLinkClient<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServerLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServerLinkFindUniqueOrThrowArgs} args - Arguments to find a ServerLink
   * @example
   * // Get one ServerLink
   * const serverLink = await prisma.serverLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServerLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServerLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServerLinkClient<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServerLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerLinkFindFirstArgs} args - Arguments to find a ServerLink
   * @example
   * // Get one ServerLink
   * const serverLink = await prisma.serverLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServerLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, ServerLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServerLinkClient<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServerLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerLinkFindFirstOrThrowArgs} args - Arguments to find a ServerLink
   * @example
   * // Get one ServerLink
   * const serverLink = await prisma.serverLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServerLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServerLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServerLinkClient<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServerLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServerLinks
   * const serverLinks = await prisma.serverLink.findMany()
   * 
   * // Get first 10 ServerLinks
   * const serverLinks = await prisma.serverLink.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serverLinkWithIdOnly = await prisma.serverLink.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServerLinkFindManyArgs>(args?: Prisma.SelectSubset<T, ServerLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServerLink.
   * @param {ServerLinkCreateArgs} args - Arguments to create a ServerLink.
   * @example
   * // Create one ServerLink
   * const ServerLink = await prisma.serverLink.create({
   *   data: {
   *     // ... data to create a ServerLink
   *   }
   * })
   * 
   */
  create<T extends ServerLinkCreateArgs>(args: Prisma.SelectSubset<T, ServerLinkCreateArgs<ExtArgs>>): Prisma.Prisma__ServerLinkClient<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServerLinks.
   * @param {ServerLinkCreateManyArgs} args - Arguments to create many ServerLinks.
   * @example
   * // Create many ServerLinks
   * const serverLink = await prisma.serverLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServerLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, ServerLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServerLinks and returns the data saved in the database.
   * @param {ServerLinkCreateManyAndReturnArgs} args - Arguments to create many ServerLinks.
   * @example
   * // Create many ServerLinks
   * const serverLink = await prisma.serverLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServerLinks and only return the `id`
   * const serverLinkWithIdOnly = await prisma.serverLink.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ServerLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ServerLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServerLink.
   * @param {ServerLinkDeleteArgs} args - Arguments to delete one ServerLink.
   * @example
   * // Delete one ServerLink
   * const ServerLink = await prisma.serverLink.delete({
   *   where: {
   *     // ... filter to delete one ServerLink
   *   }
   * })
   * 
   */
  delete<T extends ServerLinkDeleteArgs>(args: Prisma.SelectSubset<T, ServerLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__ServerLinkClient<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServerLink.
   * @param {ServerLinkUpdateArgs} args - Arguments to update one ServerLink.
   * @example
   * // Update one ServerLink
   * const serverLink = await prisma.serverLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServerLinkUpdateArgs>(args: Prisma.SelectSubset<T, ServerLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__ServerLinkClient<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServerLinks.
   * @param {ServerLinkDeleteManyArgs} args - Arguments to filter ServerLinks to delete.
   * @example
   * // Delete a few ServerLinks
   * const { count } = await prisma.serverLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServerLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServerLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServerLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServerLinks
   * const serverLink = await prisma.serverLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServerLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, ServerLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServerLinks and returns the data updated in the database.
   * @param {ServerLinkUpdateManyAndReturnArgs} args - Arguments to update many ServerLinks.
   * @example
   * // Update many ServerLinks
   * const serverLink = await prisma.serverLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServerLinks and only return the `id`
   * const serverLinkWithIdOnly = await prisma.serverLink.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ServerLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ServerLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServerLink.
   * @param {ServerLinkUpsertArgs} args - Arguments to update or create a ServerLink.
   * @example
   * // Update or create a ServerLink
   * const serverLink = await prisma.serverLink.upsert({
   *   create: {
   *     // ... data to create a ServerLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServerLink we want to update
   *   }
   * })
   */
  upsert<T extends ServerLinkUpsertArgs>(args: Prisma.SelectSubset<T, ServerLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__ServerLinkClient<runtime.Types.Result.GetResult<Prisma.$ServerLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServerLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerLinkCountArgs} args - Arguments to filter ServerLinks to count.
   * @example
   * // Count the number of ServerLinks
   * const count = await prisma.serverLink.count({
   *   where: {
   *     // ... the filter for the ServerLinks we want to count
   *   }
   * })
  **/
  count<T extends ServerLinkCountArgs>(
    args?: Prisma.Subset<T, ServerLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServerLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServerLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServerLinkAggregateArgs>(args: Prisma.Subset<T, ServerLinkAggregateArgs>): Prisma.PrismaPromise<GetServerLinkAggregateType<T>>

  /**
   * Group by ServerLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServerLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServerLinkGroupByArgs['orderBy'] }
      : { orderBy?: ServerLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServerLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServerLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServerLink model
 */
readonly fields: ServerLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServerLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServerLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  guild<T extends Prisma.GuildDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuildDefaultArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  subscription<T extends Prisma.SubscriptionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubscriptionDefaultArgs<ExtArgs>>): Prisma.Prisma__SubscriptionClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServerLink model
 */
export interface ServerLinkFieldRefs {
  readonly id: Prisma.FieldRef<"ServerLink", 'String'>
  readonly guildId: Prisma.FieldRef<"ServerLink", 'String'>
  readonly subscriptionId: Prisma.FieldRef<"ServerLink", 'String'>
  readonly linkedByUserId: Prisma.FieldRef<"ServerLink", 'String'>
  readonly lastKnownMemberCount: Prisma.FieldRef<"ServerLink", 'Int'>
  readonly memberCountCheckedAt: Prisma.FieldRef<"ServerLink", 'DateTime'>
  readonly status: Prisma.FieldRef<"ServerLink", 'ServerLinkStatus'>
  readonly linkedAt: Prisma.FieldRef<"ServerLink", 'DateTime'>
  readonly unlinkedAt: Prisma.FieldRef<"ServerLink", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ServerLink findUnique
 */
export type ServerLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
  /**
   * Filter, which ServerLink to fetch.
   */
  where: Prisma.ServerLinkWhereUniqueInput
}

/**
 * ServerLink findUniqueOrThrow
 */
export type ServerLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
  /**
   * Filter, which ServerLink to fetch.
   */
  where: Prisma.ServerLinkWhereUniqueInput
}

/**
 * ServerLink findFirst
 */
export type ServerLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
  /**
   * Filter, which ServerLink to fetch.
   */
  where?: Prisma.ServerLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServerLinks to fetch.
   */
  orderBy?: Prisma.ServerLinkOrderByWithRelationInput | Prisma.ServerLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServerLinks.
   */
  cursor?: Prisma.ServerLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServerLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServerLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServerLinks.
   */
  distinct?: Prisma.ServerLinkScalarFieldEnum | Prisma.ServerLinkScalarFieldEnum[]
}

/**
 * ServerLink findFirstOrThrow
 */
export type ServerLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
  /**
   * Filter, which ServerLink to fetch.
   */
  where?: Prisma.ServerLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServerLinks to fetch.
   */
  orderBy?: Prisma.ServerLinkOrderByWithRelationInput | Prisma.ServerLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServerLinks.
   */
  cursor?: Prisma.ServerLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServerLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServerLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServerLinks.
   */
  distinct?: Prisma.ServerLinkScalarFieldEnum | Prisma.ServerLinkScalarFieldEnum[]
}

/**
 * ServerLink findMany
 */
export type ServerLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
  /**
   * Filter, which ServerLinks to fetch.
   */
  where?: Prisma.ServerLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServerLinks to fetch.
   */
  orderBy?: Prisma.ServerLinkOrderByWithRelationInput | Prisma.ServerLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServerLinks.
   */
  cursor?: Prisma.ServerLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServerLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServerLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServerLinks.
   */
  distinct?: Prisma.ServerLinkScalarFieldEnum | Prisma.ServerLinkScalarFieldEnum[]
}

/**
 * ServerLink create
 */
export type ServerLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a ServerLink.
   */
  data: Prisma.XOR<Prisma.ServerLinkCreateInput, Prisma.ServerLinkUncheckedCreateInput>
}

/**
 * ServerLink createMany
 */
export type ServerLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServerLinks.
   */
  data: Prisma.ServerLinkCreateManyInput | Prisma.ServerLinkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServerLink createManyAndReturn
 */
export type ServerLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * The data used to create many ServerLinks.
   */
  data: Prisma.ServerLinkCreateManyInput | Prisma.ServerLinkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ServerLink update
 */
export type ServerLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a ServerLink.
   */
  data: Prisma.XOR<Prisma.ServerLinkUpdateInput, Prisma.ServerLinkUncheckedUpdateInput>
  /**
   * Choose, which ServerLink to update.
   */
  where: Prisma.ServerLinkWhereUniqueInput
}

/**
 * ServerLink updateMany
 */
export type ServerLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServerLinks.
   */
  data: Prisma.XOR<Prisma.ServerLinkUpdateManyMutationInput, Prisma.ServerLinkUncheckedUpdateManyInput>
  /**
   * Filter which ServerLinks to update
   */
  where?: Prisma.ServerLinkWhereInput
  /**
   * Limit how many ServerLinks to update.
   */
  limit?: number
}

/**
 * ServerLink updateManyAndReturn
 */
export type ServerLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * The data used to update ServerLinks.
   */
  data: Prisma.XOR<Prisma.ServerLinkUpdateManyMutationInput, Prisma.ServerLinkUncheckedUpdateManyInput>
  /**
   * Filter which ServerLinks to update
   */
  where?: Prisma.ServerLinkWhereInput
  /**
   * Limit how many ServerLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ServerLink upsert
 */
export type ServerLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the ServerLink to update in case it exists.
   */
  where: Prisma.ServerLinkWhereUniqueInput
  /**
   * In case the ServerLink found by the `where` argument doesn't exist, create a new ServerLink with this data.
   */
  create: Prisma.XOR<Prisma.ServerLinkCreateInput, Prisma.ServerLinkUncheckedCreateInput>
  /**
   * In case the ServerLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServerLinkUpdateInput, Prisma.ServerLinkUncheckedUpdateInput>
}

/**
 * ServerLink delete
 */
export type ServerLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
  /**
   * Filter which ServerLink to delete.
   */
  where: Prisma.ServerLinkWhereUniqueInput
}

/**
 * ServerLink deleteMany
 */
export type ServerLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServerLinks to delete
   */
  where?: Prisma.ServerLinkWhereInput
  /**
   * Limit how many ServerLinks to delete.
   */
  limit?: number
}

/**
 * ServerLink without action
 */
export type ServerLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerLink
   */
  select?: Prisma.ServerLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerLink
   */
  omit?: Prisma.ServerLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServerLinkInclude<ExtArgs> | null
}
