
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Plan: 'Plan',
  Guild: 'Guild',
  Settings: 'Settings',
  Template: 'Template',
  ServerLink: 'ServerLink',
  Audit: 'Audit',
  Member: 'Member',
  PointSession: 'PointSession',
  Pause: 'Pause',
  MemberFlow: 'MemberFlow',
  User: 'User',
  Subscription: 'Subscription'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const PlanScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  maxServers: 'maxServers',
  maxMembersPool: 'maxMembersPool',
  priceCents: 'priceCents',
  mercadoPagoPlanId: 'mercadoPagoPlanId',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlanScalarFieldEnum = (typeof PlanScalarFieldEnum)[keyof typeof PlanScalarFieldEnum]


export const GuildScalarFieldEnum = {
  id: 'id',
  discordId: 'discordId',
  name: 'name',
  icon: 'icon',
  ownerDiscordId: 'ownerDiscordId',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GuildScalarFieldEnum = (typeof GuildScalarFieldEnum)[keyof typeof GuildScalarFieldEnum]


export const SettingsScalarFieldEnum = {
  guildId: 'guildId',
  weeklyGoalActive: 'weeklyGoalActive',
  weeklyGoalSeconds: 'weeklyGoalSeconds',
  welcomeChannelId: 'welcomeChannelId',
  pointOpenLogChannelId: 'pointOpenLogChannelId',
  pointCloseLogChannelId: 'pointCloseLogChannelId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]


export const TemplateScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  name: 'name',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TemplateScalarFieldEnum = (typeof TemplateScalarFieldEnum)[keyof typeof TemplateScalarFieldEnum]


export const ServerLinkScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  subscriptionId: 'subscriptionId',
  linkedByUserId: 'linkedByUserId',
  lastKnownMemberCount: 'lastKnownMemberCount',
  memberCountCheckedAt: 'memberCountCheckedAt',
  status: 'status',
  linkedAt: 'linkedAt',
  unlinkedAt: 'unlinkedAt'
} as const

export type ServerLinkScalarFieldEnum = (typeof ServerLinkScalarFieldEnum)[keyof typeof ServerLinkScalarFieldEnum]


export const AuditScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  userId: 'userId',
  targetUserId: 'targetUserId',
  action: 'action',
  oldValue: 'oldValue',
  newValue: 'newValue',
  createdAt: 'createdAt'
} as const

export type AuditScalarFieldEnum = (typeof AuditScalarFieldEnum)[keyof typeof AuditScalarFieldEnum]


export const MemberScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  weeklyGoalActive: 'weeklyGoalActive',
  weeklyGoalSeconds: 'weeklyGoalSeconds',
  status: 'status',
  discordId: 'discordId',
  discordTag: 'discordTag',
  discordAvatar: 'discordAvatar',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MemberScalarFieldEnum = (typeof MemberScalarFieldEnum)[keyof typeof MemberScalarFieldEnum]


export const PointSessionScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  status: 'status',
  weeklyGoalSecondsSnapshot: 'weeklyGoalSecondsSnapshot',
  voiceChannelId: 'voiceChannelId',
  activity: 'activity',
  messageOpenLink: 'messageOpenLink',
  messageCloseLink: 'messageCloseLink',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  totalSeconds: 'totalSeconds',
  initialParticipantsIds: 'initialParticipantsIds',
  finalParticipantsIds: 'finalParticipantsIds',
  participantsCount: 'participantsCount',
  initialNotes: 'initialNotes',
  finalNotes: 'finalNotes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PointSessionScalarFieldEnum = (typeof PointSessionScalarFieldEnum)[keyof typeof PointSessionScalarFieldEnum]


export const PauseScalarFieldEnum = {
  id: 'id',
  pointSessionId: 'pointSessionId',
  status: 'status',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  durationSeconds: 'durationSeconds',
  reason: 'reason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PauseScalarFieldEnum = (typeof PauseScalarFieldEnum)[keyof typeof PauseScalarFieldEnum]


export const MemberFlowScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  userId: 'userId',
  userTag: 'userTag',
  action: 'action',
  createdAt: 'createdAt'
} as const

export type MemberFlowScalarFieldEnum = (typeof MemberFlowScalarFieldEnum)[keyof typeof MemberFlowScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  discordId: 'discordId',
  username: 'username',
  email: 'email',
  avatar: 'avatar',
  discordAccessToken: 'discordAccessToken',
  discordRefreshToken: 'discordRefreshToken',
  discordTokenExpiresAt: 'discordTokenExpiresAt',
  currentPlanId: 'currentPlanId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SubscriptionScalarFieldEnum = {
  userId: 'userId',
  planId: 'planId',
  mercadoPagoPreapprovalId: 'mercadoPagoPreapprovalId',
  currentPeriodStart: 'currentPeriodStart',
  currentPeriodEnd: 'currentPeriodEnd',
  cancelAtPeriodEnd: 'cancelAtPeriodEnd',
  trialEnd: 'trialEnd',
  cancelAt: 'cancelAt',
  canceledAt: 'canceledAt',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubscriptionScalarFieldEnum = (typeof SubscriptionScalarFieldEnum)[keyof typeof SubscriptionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

