
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MemberFlow` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model MemberFlow
 * 
 */
export type MemberFlowModel = runtime.Types.Result.DefaultSelection<Prisma.$MemberFlowPayload>

export type AggregateMemberFlow = {
  _count: MemberFlowCountAggregateOutputType | null
  _min: MemberFlowMinAggregateOutputType | null
  _max: MemberFlowMaxAggregateOutputType | null
}

export type MemberFlowMinAggregateOutputType = {
  id: string | null
  guildId: string | null
  userId: string | null
  userTag: string | null
  action: $Enums.MemberFlowAction | null
  createdAt: Date | null
}

export type MemberFlowMaxAggregateOutputType = {
  id: string | null
  guildId: string | null
  userId: string | null
  userTag: string | null
  action: $Enums.MemberFlowAction | null
  createdAt: Date | null
}

export type MemberFlowCountAggregateOutputType = {
  id: number
  guildId: number
  userId: number
  userTag: number
  action: number
  createdAt: number
  _all: number
}


export type MemberFlowMinAggregateInputType = {
  id?: true
  guildId?: true
  userId?: true
  userTag?: true
  action?: true
  createdAt?: true
}

export type MemberFlowMaxAggregateInputType = {
  id?: true
  guildId?: true
  userId?: true
  userTag?: true
  action?: true
  createdAt?: true
}

export type MemberFlowCountAggregateInputType = {
  id?: true
  guildId?: true
  userId?: true
  userTag?: true
  action?: true
  createdAt?: true
  _all?: true
}

export type MemberFlowAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MemberFlow to aggregate.
   */
  where?: Prisma.MemberFlowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MemberFlows to fetch.
   */
  orderBy?: Prisma.MemberFlowOrderByWithRelationInput | Prisma.MemberFlowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MemberFlowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MemberFlows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MemberFlows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MemberFlows
  **/
  _count?: true | MemberFlowCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MemberFlowMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MemberFlowMaxAggregateInputType
}

export type GetMemberFlowAggregateType<T extends MemberFlowAggregateArgs> = {
      [P in keyof T & keyof AggregateMemberFlow]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMemberFlow[P]>
    : Prisma.GetScalarType<T[P], AggregateMemberFlow[P]>
}




export type MemberFlowGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MemberFlowWhereInput
  orderBy?: Prisma.MemberFlowOrderByWithAggregationInput | Prisma.MemberFlowOrderByWithAggregationInput[]
  by: Prisma.MemberFlowScalarFieldEnum[] | Prisma.MemberFlowScalarFieldEnum
  having?: Prisma.MemberFlowScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MemberFlowCountAggregateInputType | true
  _min?: MemberFlowMinAggregateInputType
  _max?: MemberFlowMaxAggregateInputType
}

export type MemberFlowGroupByOutputType = {
  id: string
  guildId: string
  userId: string
  userTag: string
  action: $Enums.MemberFlowAction
  createdAt: Date
  _count: MemberFlowCountAggregateOutputType | null
  _min: MemberFlowMinAggregateOutputType | null
  _max: MemberFlowMaxAggregateOutputType | null
}

export type GetMemberFlowGroupByPayload<T extends MemberFlowGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MemberFlowGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MemberFlowGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MemberFlowGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MemberFlowGroupByOutputType[P]>
      }
    >
  >



export type MemberFlowWhereInput = {
  AND?: Prisma.MemberFlowWhereInput | Prisma.MemberFlowWhereInput[]
  OR?: Prisma.MemberFlowWhereInput[]
  NOT?: Prisma.MemberFlowWhereInput | Prisma.MemberFlowWhereInput[]
  id?: Prisma.StringFilter<"MemberFlow"> | string
  guildId?: Prisma.StringFilter<"MemberFlow"> | string
  userId?: Prisma.StringFilter<"MemberFlow"> | string
  userTag?: Prisma.StringFilter<"MemberFlow"> | string
  action?: Prisma.EnumMemberFlowActionFilter<"MemberFlow"> | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFilter<"MemberFlow"> | Date | string
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
}

export type MemberFlowOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  userTag?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  guild?: Prisma.GuildOrderByWithRelationInput
}

export type MemberFlowWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MemberFlowWhereInput | Prisma.MemberFlowWhereInput[]
  OR?: Prisma.MemberFlowWhereInput[]
  NOT?: Prisma.MemberFlowWhereInput | Prisma.MemberFlowWhereInput[]
  guildId?: Prisma.StringFilter<"MemberFlow"> | string
  userId?: Prisma.StringFilter<"MemberFlow"> | string
  userTag?: Prisma.StringFilter<"MemberFlow"> | string
  action?: Prisma.EnumMemberFlowActionFilter<"MemberFlow"> | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFilter<"MemberFlow"> | Date | string
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
}, "id">

export type MemberFlowOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  userTag?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MemberFlowCountOrderByAggregateInput
  _max?: Prisma.MemberFlowMaxOrderByAggregateInput
  _min?: Prisma.MemberFlowMinOrderByAggregateInput
}

export type MemberFlowScalarWhereWithAggregatesInput = {
  AND?: Prisma.MemberFlowScalarWhereWithAggregatesInput | Prisma.MemberFlowScalarWhereWithAggregatesInput[]
  OR?: Prisma.MemberFlowScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MemberFlowScalarWhereWithAggregatesInput | Prisma.MemberFlowScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MemberFlow"> | string
  guildId?: Prisma.StringWithAggregatesFilter<"MemberFlow"> | string
  userId?: Prisma.StringWithAggregatesFilter<"MemberFlow"> | string
  userTag?: Prisma.StringWithAggregatesFilter<"MemberFlow"> | string
  action?: Prisma.EnumMemberFlowActionWithAggregatesFilter<"MemberFlow"> | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MemberFlow"> | Date | string
}

export type MemberFlowCreateInput = {
  id?: string
  userId: string
  userTag: string
  action: $Enums.MemberFlowAction
  createdAt?: Date | string
  guild: Prisma.GuildCreateNestedOneWithoutMemberFlowInput
}

export type MemberFlowUncheckedCreateInput = {
  id?: string
  guildId: string
  userId: string
  userTag: string
  action: $Enums.MemberFlowAction
  createdAt?: Date | string
}

export type MemberFlowUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  userTag?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMemberFlowActionFieldUpdateOperationsInput | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  guild?: Prisma.GuildUpdateOneRequiredWithoutMemberFlowNestedInput
}

export type MemberFlowUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  userTag?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMemberFlowActionFieldUpdateOperationsInput | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberFlowCreateManyInput = {
  id?: string
  guildId: string
  userId: string
  userTag: string
  action: $Enums.MemberFlowAction
  createdAt?: Date | string
}

export type MemberFlowUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  userTag?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMemberFlowActionFieldUpdateOperationsInput | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberFlowUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  userTag?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMemberFlowActionFieldUpdateOperationsInput | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberFlowListRelationFilter = {
  every?: Prisma.MemberFlowWhereInput
  some?: Prisma.MemberFlowWhereInput
  none?: Prisma.MemberFlowWhereInput
}

export type MemberFlowOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MemberFlowCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  userTag?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MemberFlowMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  userTag?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MemberFlowMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  userTag?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MemberFlowCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.MemberFlowCreateWithoutGuildInput, Prisma.MemberFlowUncheckedCreateWithoutGuildInput> | Prisma.MemberFlowCreateWithoutGuildInput[] | Prisma.MemberFlowUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.MemberFlowCreateOrConnectWithoutGuildInput | Prisma.MemberFlowCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.MemberFlowCreateManyGuildInputEnvelope
  connect?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
}

export type MemberFlowUncheckedCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.MemberFlowCreateWithoutGuildInput, Prisma.MemberFlowUncheckedCreateWithoutGuildInput> | Prisma.MemberFlowCreateWithoutGuildInput[] | Prisma.MemberFlowUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.MemberFlowCreateOrConnectWithoutGuildInput | Prisma.MemberFlowCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.MemberFlowCreateManyGuildInputEnvelope
  connect?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
}

export type MemberFlowUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.MemberFlowCreateWithoutGuildInput, Prisma.MemberFlowUncheckedCreateWithoutGuildInput> | Prisma.MemberFlowCreateWithoutGuildInput[] | Prisma.MemberFlowUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.MemberFlowCreateOrConnectWithoutGuildInput | Prisma.MemberFlowCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.MemberFlowUpsertWithWhereUniqueWithoutGuildInput | Prisma.MemberFlowUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.MemberFlowCreateManyGuildInputEnvelope
  set?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
  disconnect?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
  delete?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
  connect?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
  update?: Prisma.MemberFlowUpdateWithWhereUniqueWithoutGuildInput | Prisma.MemberFlowUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.MemberFlowUpdateManyWithWhereWithoutGuildInput | Prisma.MemberFlowUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.MemberFlowScalarWhereInput | Prisma.MemberFlowScalarWhereInput[]
}

export type MemberFlowUncheckedUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.MemberFlowCreateWithoutGuildInput, Prisma.MemberFlowUncheckedCreateWithoutGuildInput> | Prisma.MemberFlowCreateWithoutGuildInput[] | Prisma.MemberFlowUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.MemberFlowCreateOrConnectWithoutGuildInput | Prisma.MemberFlowCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.MemberFlowUpsertWithWhereUniqueWithoutGuildInput | Prisma.MemberFlowUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.MemberFlowCreateManyGuildInputEnvelope
  set?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
  disconnect?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
  delete?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
  connect?: Prisma.MemberFlowWhereUniqueInput | Prisma.MemberFlowWhereUniqueInput[]
  update?: Prisma.MemberFlowUpdateWithWhereUniqueWithoutGuildInput | Prisma.MemberFlowUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.MemberFlowUpdateManyWithWhereWithoutGuildInput | Prisma.MemberFlowUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.MemberFlowScalarWhereInput | Prisma.MemberFlowScalarWhereInput[]
}

export type EnumMemberFlowActionFieldUpdateOperationsInput = {
  set?: $Enums.MemberFlowAction
}

export type MemberFlowCreateWithoutGuildInput = {
  id?: string
  userId: string
  userTag: string
  action: $Enums.MemberFlowAction
  createdAt?: Date | string
}

export type MemberFlowUncheckedCreateWithoutGuildInput = {
  id?: string
  userId: string
  userTag: string
  action: $Enums.MemberFlowAction
  createdAt?: Date | string
}

export type MemberFlowCreateOrConnectWithoutGuildInput = {
  where: Prisma.MemberFlowWhereUniqueInput
  create: Prisma.XOR<Prisma.MemberFlowCreateWithoutGuildInput, Prisma.MemberFlowUncheckedCreateWithoutGuildInput>
}

export type MemberFlowCreateManyGuildInputEnvelope = {
  data: Prisma.MemberFlowCreateManyGuildInput | Prisma.MemberFlowCreateManyGuildInput[]
  skipDuplicates?: boolean
}

export type MemberFlowUpsertWithWhereUniqueWithoutGuildInput = {
  where: Prisma.MemberFlowWhereUniqueInput
  update: Prisma.XOR<Prisma.MemberFlowUpdateWithoutGuildInput, Prisma.MemberFlowUncheckedUpdateWithoutGuildInput>
  create: Prisma.XOR<Prisma.MemberFlowCreateWithoutGuildInput, Prisma.MemberFlowUncheckedCreateWithoutGuildInput>
}

export type MemberFlowUpdateWithWhereUniqueWithoutGuildInput = {
  where: Prisma.MemberFlowWhereUniqueInput
  data: Prisma.XOR<Prisma.MemberFlowUpdateWithoutGuildInput, Prisma.MemberFlowUncheckedUpdateWithoutGuildInput>
}

export type MemberFlowUpdateManyWithWhereWithoutGuildInput = {
  where: Prisma.MemberFlowScalarWhereInput
  data: Prisma.XOR<Prisma.MemberFlowUpdateManyMutationInput, Prisma.MemberFlowUncheckedUpdateManyWithoutGuildInput>
}

export type MemberFlowScalarWhereInput = {
  AND?: Prisma.MemberFlowScalarWhereInput | Prisma.MemberFlowScalarWhereInput[]
  OR?: Prisma.MemberFlowScalarWhereInput[]
  NOT?: Prisma.MemberFlowScalarWhereInput | Prisma.MemberFlowScalarWhereInput[]
  id?: Prisma.StringFilter<"MemberFlow"> | string
  guildId?: Prisma.StringFilter<"MemberFlow"> | string
  userId?: Prisma.StringFilter<"MemberFlow"> | string
  userTag?: Prisma.StringFilter<"MemberFlow"> | string
  action?: Prisma.EnumMemberFlowActionFilter<"MemberFlow"> | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFilter<"MemberFlow"> | Date | string
}

export type MemberFlowCreateManyGuildInput = {
  id?: string
  userId: string
  userTag: string
  action: $Enums.MemberFlowAction
  createdAt?: Date | string
}

export type MemberFlowUpdateWithoutGuildInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  userTag?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMemberFlowActionFieldUpdateOperationsInput | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberFlowUncheckedUpdateWithoutGuildInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  userTag?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMemberFlowActionFieldUpdateOperationsInput | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberFlowUncheckedUpdateManyWithoutGuildInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  userTag?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMemberFlowActionFieldUpdateOperationsInput | $Enums.MemberFlowAction
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MemberFlowSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  userId?: boolean
  userTag?: boolean
  action?: boolean
  createdAt?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}, ExtArgs["result"]["memberFlow"]>

export type MemberFlowSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  userId?: boolean
  userTag?: boolean
  action?: boolean
  createdAt?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}, ExtArgs["result"]["memberFlow"]>

export type MemberFlowSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  userId?: boolean
  userTag?: boolean
  action?: boolean
  createdAt?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}, ExtArgs["result"]["memberFlow"]>

export type MemberFlowSelectScalar = {
  id?: boolean
  guildId?: boolean
  userId?: boolean
  userTag?: boolean
  action?: boolean
  createdAt?: boolean
}

export type MemberFlowOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guildId" | "userId" | "userTag" | "action" | "createdAt", ExtArgs["result"]["memberFlow"]>
export type MemberFlowInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}
export type MemberFlowIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}
export type MemberFlowIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}

export type $MemberFlowPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MemberFlow"
  objects: {
    guild: Prisma.$GuildPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    guildId: string
    userId: string
    userTag: string
    action: $Enums.MemberFlowAction
    createdAt: Date
  }, ExtArgs["result"]["memberFlow"]>
  composites: {}
}

export type MemberFlowGetPayload<S extends boolean | null | undefined | MemberFlowDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload, S>

export type MemberFlowCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MemberFlowFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MemberFlowCountAggregateInputType | true
  }

export interface MemberFlowDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MemberFlow'], meta: { name: 'MemberFlow' } }
  /**
   * Find zero or one MemberFlow that matches the filter.
   * @param {MemberFlowFindUniqueArgs} args - Arguments to find a MemberFlow
   * @example
   * // Get one MemberFlow
   * const memberFlow = await prisma.memberFlow.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MemberFlowFindUniqueArgs>(args: Prisma.SelectSubset<T, MemberFlowFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MemberFlowClient<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MemberFlow that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MemberFlowFindUniqueOrThrowArgs} args - Arguments to find a MemberFlow
   * @example
   * // Get one MemberFlow
   * const memberFlow = await prisma.memberFlow.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MemberFlowFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MemberFlowFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MemberFlowClient<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MemberFlow that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberFlowFindFirstArgs} args - Arguments to find a MemberFlow
   * @example
   * // Get one MemberFlow
   * const memberFlow = await prisma.memberFlow.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MemberFlowFindFirstArgs>(args?: Prisma.SelectSubset<T, MemberFlowFindFirstArgs<ExtArgs>>): Prisma.Prisma__MemberFlowClient<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MemberFlow that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberFlowFindFirstOrThrowArgs} args - Arguments to find a MemberFlow
   * @example
   * // Get one MemberFlow
   * const memberFlow = await prisma.memberFlow.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MemberFlowFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MemberFlowFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MemberFlowClient<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MemberFlows that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberFlowFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MemberFlows
   * const memberFlows = await prisma.memberFlow.findMany()
   * 
   * // Get first 10 MemberFlows
   * const memberFlows = await prisma.memberFlow.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const memberFlowWithIdOnly = await prisma.memberFlow.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MemberFlowFindManyArgs>(args?: Prisma.SelectSubset<T, MemberFlowFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MemberFlow.
   * @param {MemberFlowCreateArgs} args - Arguments to create a MemberFlow.
   * @example
   * // Create one MemberFlow
   * const MemberFlow = await prisma.memberFlow.create({
   *   data: {
   *     // ... data to create a MemberFlow
   *   }
   * })
   * 
   */
  create<T extends MemberFlowCreateArgs>(args: Prisma.SelectSubset<T, MemberFlowCreateArgs<ExtArgs>>): Prisma.Prisma__MemberFlowClient<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MemberFlows.
   * @param {MemberFlowCreateManyArgs} args - Arguments to create many MemberFlows.
   * @example
   * // Create many MemberFlows
   * const memberFlow = await prisma.memberFlow.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MemberFlowCreateManyArgs>(args?: Prisma.SelectSubset<T, MemberFlowCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MemberFlows and returns the data saved in the database.
   * @param {MemberFlowCreateManyAndReturnArgs} args - Arguments to create many MemberFlows.
   * @example
   * // Create many MemberFlows
   * const memberFlow = await prisma.memberFlow.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MemberFlows and only return the `id`
   * const memberFlowWithIdOnly = await prisma.memberFlow.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MemberFlowCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MemberFlowCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MemberFlow.
   * @param {MemberFlowDeleteArgs} args - Arguments to delete one MemberFlow.
   * @example
   * // Delete one MemberFlow
   * const MemberFlow = await prisma.memberFlow.delete({
   *   where: {
   *     // ... filter to delete one MemberFlow
   *   }
   * })
   * 
   */
  delete<T extends MemberFlowDeleteArgs>(args: Prisma.SelectSubset<T, MemberFlowDeleteArgs<ExtArgs>>): Prisma.Prisma__MemberFlowClient<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MemberFlow.
   * @param {MemberFlowUpdateArgs} args - Arguments to update one MemberFlow.
   * @example
   * // Update one MemberFlow
   * const memberFlow = await prisma.memberFlow.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MemberFlowUpdateArgs>(args: Prisma.SelectSubset<T, MemberFlowUpdateArgs<ExtArgs>>): Prisma.Prisma__MemberFlowClient<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MemberFlows.
   * @param {MemberFlowDeleteManyArgs} args - Arguments to filter MemberFlows to delete.
   * @example
   * // Delete a few MemberFlows
   * const { count } = await prisma.memberFlow.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MemberFlowDeleteManyArgs>(args?: Prisma.SelectSubset<T, MemberFlowDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MemberFlows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberFlowUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MemberFlows
   * const memberFlow = await prisma.memberFlow.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MemberFlowUpdateManyArgs>(args: Prisma.SelectSubset<T, MemberFlowUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MemberFlows and returns the data updated in the database.
   * @param {MemberFlowUpdateManyAndReturnArgs} args - Arguments to update many MemberFlows.
   * @example
   * // Update many MemberFlows
   * const memberFlow = await prisma.memberFlow.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MemberFlows and only return the `id`
   * const memberFlowWithIdOnly = await prisma.memberFlow.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MemberFlowUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MemberFlowUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MemberFlow.
   * @param {MemberFlowUpsertArgs} args - Arguments to update or create a MemberFlow.
   * @example
   * // Update or create a MemberFlow
   * const memberFlow = await prisma.memberFlow.upsert({
   *   create: {
   *     // ... data to create a MemberFlow
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MemberFlow we want to update
   *   }
   * })
   */
  upsert<T extends MemberFlowUpsertArgs>(args: Prisma.SelectSubset<T, MemberFlowUpsertArgs<ExtArgs>>): Prisma.Prisma__MemberFlowClient<runtime.Types.Result.GetResult<Prisma.$MemberFlowPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MemberFlows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberFlowCountArgs} args - Arguments to filter MemberFlows to count.
   * @example
   * // Count the number of MemberFlows
   * const count = await prisma.memberFlow.count({
   *   where: {
   *     // ... the filter for the MemberFlows we want to count
   *   }
   * })
  **/
  count<T extends MemberFlowCountArgs>(
    args?: Prisma.Subset<T, MemberFlowCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MemberFlowCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MemberFlow.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberFlowAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MemberFlowAggregateArgs>(args: Prisma.Subset<T, MemberFlowAggregateArgs>): Prisma.PrismaPromise<GetMemberFlowAggregateType<T>>

  /**
   * Group by MemberFlow.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberFlowGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MemberFlowGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MemberFlowGroupByArgs['orderBy'] }
      : { orderBy?: MemberFlowGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MemberFlowGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMemberFlowGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MemberFlow model
 */
readonly fields: MemberFlowFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MemberFlow.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MemberFlowClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  guild<T extends Prisma.GuildDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuildDefaultArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MemberFlow model
 */
export interface MemberFlowFieldRefs {
  readonly id: Prisma.FieldRef<"MemberFlow", 'String'>
  readonly guildId: Prisma.FieldRef<"MemberFlow", 'String'>
  readonly userId: Prisma.FieldRef<"MemberFlow", 'String'>
  readonly userTag: Prisma.FieldRef<"MemberFlow", 'String'>
  readonly action: Prisma.FieldRef<"MemberFlow", 'MemberFlowAction'>
  readonly createdAt: Prisma.FieldRef<"MemberFlow", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MemberFlow findUnique
 */
export type MemberFlowFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
  /**
   * Filter, which MemberFlow to fetch.
   */
  where: Prisma.MemberFlowWhereUniqueInput
}

/**
 * MemberFlow findUniqueOrThrow
 */
export type MemberFlowFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
  /**
   * Filter, which MemberFlow to fetch.
   */
  where: Prisma.MemberFlowWhereUniqueInput
}

/**
 * MemberFlow findFirst
 */
export type MemberFlowFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
  /**
   * Filter, which MemberFlow to fetch.
   */
  where?: Prisma.MemberFlowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MemberFlows to fetch.
   */
  orderBy?: Prisma.MemberFlowOrderByWithRelationInput | Prisma.MemberFlowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MemberFlows.
   */
  cursor?: Prisma.MemberFlowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MemberFlows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MemberFlows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MemberFlows.
   */
  distinct?: Prisma.MemberFlowScalarFieldEnum | Prisma.MemberFlowScalarFieldEnum[]
}

/**
 * MemberFlow findFirstOrThrow
 */
export type MemberFlowFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
  /**
   * Filter, which MemberFlow to fetch.
   */
  where?: Prisma.MemberFlowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MemberFlows to fetch.
   */
  orderBy?: Prisma.MemberFlowOrderByWithRelationInput | Prisma.MemberFlowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MemberFlows.
   */
  cursor?: Prisma.MemberFlowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MemberFlows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MemberFlows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MemberFlows.
   */
  distinct?: Prisma.MemberFlowScalarFieldEnum | Prisma.MemberFlowScalarFieldEnum[]
}

/**
 * MemberFlow findMany
 */
export type MemberFlowFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
  /**
   * Filter, which MemberFlows to fetch.
   */
  where?: Prisma.MemberFlowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MemberFlows to fetch.
   */
  orderBy?: Prisma.MemberFlowOrderByWithRelationInput | Prisma.MemberFlowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MemberFlows.
   */
  cursor?: Prisma.MemberFlowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MemberFlows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MemberFlows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MemberFlows.
   */
  distinct?: Prisma.MemberFlowScalarFieldEnum | Prisma.MemberFlowScalarFieldEnum[]
}

/**
 * MemberFlow create
 */
export type MemberFlowCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
  /**
   * The data needed to create a MemberFlow.
   */
  data: Prisma.XOR<Prisma.MemberFlowCreateInput, Prisma.MemberFlowUncheckedCreateInput>
}

/**
 * MemberFlow createMany
 */
export type MemberFlowCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MemberFlows.
   */
  data: Prisma.MemberFlowCreateManyInput | Prisma.MemberFlowCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MemberFlow createManyAndReturn
 */
export type MemberFlowCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * The data used to create many MemberFlows.
   */
  data: Prisma.MemberFlowCreateManyInput | Prisma.MemberFlowCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MemberFlow update
 */
export type MemberFlowUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
  /**
   * The data needed to update a MemberFlow.
   */
  data: Prisma.XOR<Prisma.MemberFlowUpdateInput, Prisma.MemberFlowUncheckedUpdateInput>
  /**
   * Choose, which MemberFlow to update.
   */
  where: Prisma.MemberFlowWhereUniqueInput
}

/**
 * MemberFlow updateMany
 */
export type MemberFlowUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MemberFlows.
   */
  data: Prisma.XOR<Prisma.MemberFlowUpdateManyMutationInput, Prisma.MemberFlowUncheckedUpdateManyInput>
  /**
   * Filter which MemberFlows to update
   */
  where?: Prisma.MemberFlowWhereInput
  /**
   * Limit how many MemberFlows to update.
   */
  limit?: number
}

/**
 * MemberFlow updateManyAndReturn
 */
export type MemberFlowUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * The data used to update MemberFlows.
   */
  data: Prisma.XOR<Prisma.MemberFlowUpdateManyMutationInput, Prisma.MemberFlowUncheckedUpdateManyInput>
  /**
   * Filter which MemberFlows to update
   */
  where?: Prisma.MemberFlowWhereInput
  /**
   * Limit how many MemberFlows to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MemberFlow upsert
 */
export type MemberFlowUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
  /**
   * The filter to search for the MemberFlow to update in case it exists.
   */
  where: Prisma.MemberFlowWhereUniqueInput
  /**
   * In case the MemberFlow found by the `where` argument doesn't exist, create a new MemberFlow with this data.
   */
  create: Prisma.XOR<Prisma.MemberFlowCreateInput, Prisma.MemberFlowUncheckedCreateInput>
  /**
   * In case the MemberFlow was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MemberFlowUpdateInput, Prisma.MemberFlowUncheckedUpdateInput>
}

/**
 * MemberFlow delete
 */
export type MemberFlowDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
  /**
   * Filter which MemberFlow to delete.
   */
  where: Prisma.MemberFlowWhereUniqueInput
}

/**
 * MemberFlow deleteMany
 */
export type MemberFlowDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MemberFlows to delete
   */
  where?: Prisma.MemberFlowWhereInput
  /**
   * Limit how many MemberFlows to delete.
   */
  limit?: number
}

/**
 * MemberFlow without action
 */
export type MemberFlowDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberFlow
   */
  select?: Prisma.MemberFlowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberFlow
   */
  omit?: Prisma.MemberFlowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberFlowInclude<ExtArgs> | null
}
