
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PointSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PointSession
 * 
 */
export type PointSessionModel = runtime.Types.Result.DefaultSelection<Prisma.$PointSessionPayload>

export type AggregatePointSession = {
  _count: PointSessionCountAggregateOutputType | null
  _avg: PointSessionAvgAggregateOutputType | null
  _sum: PointSessionSumAggregateOutputType | null
  _min: PointSessionMinAggregateOutputType | null
  _max: PointSessionMaxAggregateOutputType | null
}

export type PointSessionAvgAggregateOutputType = {
  weeklyGoalSecondsSnapshot: number | null
  totalSeconds: number | null
  participantsCount: number | null
}

export type PointSessionSumAggregateOutputType = {
  weeklyGoalSecondsSnapshot: number | null
  totalSeconds: number | null
  participantsCount: number | null
}

export type PointSessionMinAggregateOutputType = {
  id: string | null
  memberId: string | null
  status: $Enums.PointSessionStatus | null
  weeklyGoalSecondsSnapshot: number | null
  voiceChannelId: string | null
  activity: string | null
  messageOpenLink: string | null
  messageCloseLink: string | null
  startedAt: Date | null
  endedAt: Date | null
  totalSeconds: number | null
  participantsCount: number | null
  initialNotes: string | null
  finalNotes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PointSessionMaxAggregateOutputType = {
  id: string | null
  memberId: string | null
  status: $Enums.PointSessionStatus | null
  weeklyGoalSecondsSnapshot: number | null
  voiceChannelId: string | null
  activity: string | null
  messageOpenLink: string | null
  messageCloseLink: string | null
  startedAt: Date | null
  endedAt: Date | null
  totalSeconds: number | null
  participantsCount: number | null
  initialNotes: string | null
  finalNotes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PointSessionCountAggregateOutputType = {
  id: number
  memberId: number
  status: number
  weeklyGoalSecondsSnapshot: number
  voiceChannelId: number
  activity: number
  messageOpenLink: number
  messageCloseLink: number
  startedAt: number
  endedAt: number
  totalSeconds: number
  initialParticipantsIds: number
  finalParticipantsIds: number
  participantsCount: number
  initialNotes: number
  finalNotes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PointSessionAvgAggregateInputType = {
  weeklyGoalSecondsSnapshot?: true
  totalSeconds?: true
  participantsCount?: true
}

export type PointSessionSumAggregateInputType = {
  weeklyGoalSecondsSnapshot?: true
  totalSeconds?: true
  participantsCount?: true
}

export type PointSessionMinAggregateInputType = {
  id?: true
  memberId?: true
  status?: true
  weeklyGoalSecondsSnapshot?: true
  voiceChannelId?: true
  activity?: true
  messageOpenLink?: true
  messageCloseLink?: true
  startedAt?: true
  endedAt?: true
  totalSeconds?: true
  participantsCount?: true
  initialNotes?: true
  finalNotes?: true
  createdAt?: true
  updatedAt?: true
}

export type PointSessionMaxAggregateInputType = {
  id?: true
  memberId?: true
  status?: true
  weeklyGoalSecondsSnapshot?: true
  voiceChannelId?: true
  activity?: true
  messageOpenLink?: true
  messageCloseLink?: true
  startedAt?: true
  endedAt?: true
  totalSeconds?: true
  participantsCount?: true
  initialNotes?: true
  finalNotes?: true
  createdAt?: true
  updatedAt?: true
}

export type PointSessionCountAggregateInputType = {
  id?: true
  memberId?: true
  status?: true
  weeklyGoalSecondsSnapshot?: true
  voiceChannelId?: true
  activity?: true
  messageOpenLink?: true
  messageCloseLink?: true
  startedAt?: true
  endedAt?: true
  totalSeconds?: true
  initialParticipantsIds?: true
  finalParticipantsIds?: true
  participantsCount?: true
  initialNotes?: true
  finalNotes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PointSessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PointSession to aggregate.
   */
  where?: Prisma.PointSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointSessions to fetch.
   */
  orderBy?: Prisma.PointSessionOrderByWithRelationInput | Prisma.PointSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PointSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PointSessions
  **/
  _count?: true | PointSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PointSessionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PointSessionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PointSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PointSessionMaxAggregateInputType
}

export type GetPointSessionAggregateType<T extends PointSessionAggregateArgs> = {
      [P in keyof T & keyof AggregatePointSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePointSession[P]>
    : Prisma.GetScalarType<T[P], AggregatePointSession[P]>
}




export type PointSessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PointSessionWhereInput
  orderBy?: Prisma.PointSessionOrderByWithAggregationInput | Prisma.PointSessionOrderByWithAggregationInput[]
  by: Prisma.PointSessionScalarFieldEnum[] | Prisma.PointSessionScalarFieldEnum
  having?: Prisma.PointSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PointSessionCountAggregateInputType | true
  _avg?: PointSessionAvgAggregateInputType
  _sum?: PointSessionSumAggregateInputType
  _min?: PointSessionMinAggregateInputType
  _max?: PointSessionMaxAggregateInputType
}

export type PointSessionGroupByOutputType = {
  id: string
  memberId: string
  status: $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot: number | null
  voiceChannelId: string | null
  activity: string | null
  messageOpenLink: string | null
  messageCloseLink: string | null
  startedAt: Date
  endedAt: Date | null
  totalSeconds: number | null
  initialParticipantsIds: string[]
  finalParticipantsIds: string[]
  participantsCount: number | null
  initialNotes: string | null
  finalNotes: string | null
  createdAt: Date
  updatedAt: Date
  _count: PointSessionCountAggregateOutputType | null
  _avg: PointSessionAvgAggregateOutputType | null
  _sum: PointSessionSumAggregateOutputType | null
  _min: PointSessionMinAggregateOutputType | null
  _max: PointSessionMaxAggregateOutputType | null
}

export type GetPointSessionGroupByPayload<T extends PointSessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PointSessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PointSessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PointSessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PointSessionGroupByOutputType[P]>
      }
    >
  >



export type PointSessionWhereInput = {
  AND?: Prisma.PointSessionWhereInput | Prisma.PointSessionWhereInput[]
  OR?: Prisma.PointSessionWhereInput[]
  NOT?: Prisma.PointSessionWhereInput | Prisma.PointSessionWhereInput[]
  id?: Prisma.StringFilter<"PointSession"> | string
  memberId?: Prisma.StringFilter<"PointSession"> | string
  status?: Prisma.EnumPointSessionStatusFilter<"PointSession"> | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.IntNullableFilter<"PointSession"> | number | null
  voiceChannelId?: Prisma.StringNullableFilter<"PointSession"> | string | null
  activity?: Prisma.StringNullableFilter<"PointSession"> | string | null
  messageOpenLink?: Prisma.StringNullableFilter<"PointSession"> | string | null
  messageCloseLink?: Prisma.StringNullableFilter<"PointSession"> | string | null
  startedAt?: Prisma.DateTimeFilter<"PointSession"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"PointSession"> | Date | string | null
  totalSeconds?: Prisma.IntNullableFilter<"PointSession"> | number | null
  initialParticipantsIds?: Prisma.StringNullableListFilter<"PointSession">
  finalParticipantsIds?: Prisma.StringNullableListFilter<"PointSession">
  participantsCount?: Prisma.IntNullableFilter<"PointSession"> | number | null
  initialNotes?: Prisma.StringNullableFilter<"PointSession"> | string | null
  finalNotes?: Prisma.StringNullableFilter<"PointSession"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PointSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PointSession"> | Date | string
  member?: Prisma.XOR<Prisma.MemberScalarRelationFilter, Prisma.MemberWhereInput>
  pauses?: Prisma.PauseListRelationFilter
}

export type PointSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  weeklyGoalSecondsSnapshot?: Prisma.SortOrderInput | Prisma.SortOrder
  voiceChannelId?: Prisma.SortOrderInput | Prisma.SortOrder
  activity?: Prisma.SortOrderInput | Prisma.SortOrder
  messageOpenLink?: Prisma.SortOrderInput | Prisma.SortOrder
  messageCloseLink?: Prisma.SortOrderInput | Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  totalSeconds?: Prisma.SortOrderInput | Prisma.SortOrder
  initialParticipantsIds?: Prisma.SortOrder
  finalParticipantsIds?: Prisma.SortOrder
  participantsCount?: Prisma.SortOrderInput | Prisma.SortOrder
  initialNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  finalNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  member?: Prisma.MemberOrderByWithRelationInput
  pauses?: Prisma.PauseOrderByRelationAggregateInput
}

export type PointSessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PointSessionWhereInput | Prisma.PointSessionWhereInput[]
  OR?: Prisma.PointSessionWhereInput[]
  NOT?: Prisma.PointSessionWhereInput | Prisma.PointSessionWhereInput[]
  memberId?: Prisma.StringFilter<"PointSession"> | string
  status?: Prisma.EnumPointSessionStatusFilter<"PointSession"> | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.IntNullableFilter<"PointSession"> | number | null
  voiceChannelId?: Prisma.StringNullableFilter<"PointSession"> | string | null
  activity?: Prisma.StringNullableFilter<"PointSession"> | string | null
  messageOpenLink?: Prisma.StringNullableFilter<"PointSession"> | string | null
  messageCloseLink?: Prisma.StringNullableFilter<"PointSession"> | string | null
  startedAt?: Prisma.DateTimeFilter<"PointSession"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"PointSession"> | Date | string | null
  totalSeconds?: Prisma.IntNullableFilter<"PointSession"> | number | null
  initialParticipantsIds?: Prisma.StringNullableListFilter<"PointSession">
  finalParticipantsIds?: Prisma.StringNullableListFilter<"PointSession">
  participantsCount?: Prisma.IntNullableFilter<"PointSession"> | number | null
  initialNotes?: Prisma.StringNullableFilter<"PointSession"> | string | null
  finalNotes?: Prisma.StringNullableFilter<"PointSession"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PointSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PointSession"> | Date | string
  member?: Prisma.XOR<Prisma.MemberScalarRelationFilter, Prisma.MemberWhereInput>
  pauses?: Prisma.PauseListRelationFilter
}, "id">

export type PointSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  weeklyGoalSecondsSnapshot?: Prisma.SortOrderInput | Prisma.SortOrder
  voiceChannelId?: Prisma.SortOrderInput | Prisma.SortOrder
  activity?: Prisma.SortOrderInput | Prisma.SortOrder
  messageOpenLink?: Prisma.SortOrderInput | Prisma.SortOrder
  messageCloseLink?: Prisma.SortOrderInput | Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  totalSeconds?: Prisma.SortOrderInput | Prisma.SortOrder
  initialParticipantsIds?: Prisma.SortOrder
  finalParticipantsIds?: Prisma.SortOrder
  participantsCount?: Prisma.SortOrderInput | Prisma.SortOrder
  initialNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  finalNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PointSessionCountOrderByAggregateInput
  _avg?: Prisma.PointSessionAvgOrderByAggregateInput
  _max?: Prisma.PointSessionMaxOrderByAggregateInput
  _min?: Prisma.PointSessionMinOrderByAggregateInput
  _sum?: Prisma.PointSessionSumOrderByAggregateInput
}

export type PointSessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.PointSessionScalarWhereWithAggregatesInput | Prisma.PointSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.PointSessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PointSessionScalarWhereWithAggregatesInput | Prisma.PointSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PointSession"> | string
  memberId?: Prisma.StringWithAggregatesFilter<"PointSession"> | string
  status?: Prisma.EnumPointSessionStatusWithAggregatesFilter<"PointSession"> | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.IntNullableWithAggregatesFilter<"PointSession"> | number | null
  voiceChannelId?: Prisma.StringNullableWithAggregatesFilter<"PointSession"> | string | null
  activity?: Prisma.StringNullableWithAggregatesFilter<"PointSession"> | string | null
  messageOpenLink?: Prisma.StringNullableWithAggregatesFilter<"PointSession"> | string | null
  messageCloseLink?: Prisma.StringNullableWithAggregatesFilter<"PointSession"> | string | null
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"PointSession"> | Date | string
  endedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PointSession"> | Date | string | null
  totalSeconds?: Prisma.IntNullableWithAggregatesFilter<"PointSession"> | number | null
  initialParticipantsIds?: Prisma.StringNullableListFilter<"PointSession">
  finalParticipantsIds?: Prisma.StringNullableListFilter<"PointSession">
  participantsCount?: Prisma.IntNullableWithAggregatesFilter<"PointSession"> | number | null
  initialNotes?: Prisma.StringNullableWithAggregatesFilter<"PointSession"> | string | null
  finalNotes?: Prisma.StringNullableWithAggregatesFilter<"PointSession"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PointSession"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PointSession"> | Date | string
}

export type PointSessionCreateInput = {
  id?: string
  status?: $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: number | null
  voiceChannelId?: string | null
  activity?: string | null
  messageOpenLink?: string | null
  messageCloseLink?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  totalSeconds?: number | null
  initialParticipantsIds?: Prisma.PointSessionCreateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionCreatefinalParticipantsIdsInput | string[]
  participantsCount?: number | null
  initialNotes?: string | null
  finalNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutPointSessionsInput
  pauses?: Prisma.PauseCreateNestedManyWithoutPointSessionInput
}

export type PointSessionUncheckedCreateInput = {
  id?: string
  memberId: string
  status?: $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: number | null
  voiceChannelId?: string | null
  activity?: string | null
  messageOpenLink?: string | null
  messageCloseLink?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  totalSeconds?: number | null
  initialParticipantsIds?: Prisma.PointSessionCreateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionCreatefinalParticipantsIdsInput | string[]
  participantsCount?: number | null
  initialNotes?: string | null
  finalNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  pauses?: Prisma.PauseUncheckedCreateNestedManyWithoutPointSessionInput
}

export type PointSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPointSessionStatusFieldUpdateOperationsInput | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  voiceChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageOpenLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageCloseLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  totalSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialParticipantsIds?: Prisma.PointSessionUpdateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionUpdatefinalParticipantsIdsInput | string[]
  participantsCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  finalNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutPointSessionsNestedInput
  pauses?: Prisma.PauseUpdateManyWithoutPointSessionNestedInput
}

export type PointSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPointSessionStatusFieldUpdateOperationsInput | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  voiceChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageOpenLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageCloseLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  totalSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialParticipantsIds?: Prisma.PointSessionUpdateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionUpdatefinalParticipantsIdsInput | string[]
  participantsCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  finalNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pauses?: Prisma.PauseUncheckedUpdateManyWithoutPointSessionNestedInput
}

export type PointSessionCreateManyInput = {
  id?: string
  memberId: string
  status?: $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: number | null
  voiceChannelId?: string | null
  activity?: string | null
  messageOpenLink?: string | null
  messageCloseLink?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  totalSeconds?: number | null
  initialParticipantsIds?: Prisma.PointSessionCreateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionCreatefinalParticipantsIdsInput | string[]
  participantsCount?: number | null
  initialNotes?: string | null
  finalNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PointSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPointSessionStatusFieldUpdateOperationsInput | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  voiceChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageOpenLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageCloseLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  totalSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialParticipantsIds?: Prisma.PointSessionUpdateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionUpdatefinalParticipantsIdsInput | string[]
  participantsCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  finalNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PointSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPointSessionStatusFieldUpdateOperationsInput | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  voiceChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageOpenLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageCloseLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  totalSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialParticipantsIds?: Prisma.PointSessionUpdateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionUpdatefinalParticipantsIdsInput | string[]
  participantsCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  finalNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PointSessionListRelationFilter = {
  every?: Prisma.PointSessionWhereInput
  some?: Prisma.PointSessionWhereInput
  none?: Prisma.PointSessionWhereInput
}

export type PointSessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type PointSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  weeklyGoalSecondsSnapshot?: Prisma.SortOrder
  voiceChannelId?: Prisma.SortOrder
  activity?: Prisma.SortOrder
  messageOpenLink?: Prisma.SortOrder
  messageCloseLink?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  totalSeconds?: Prisma.SortOrder
  initialParticipantsIds?: Prisma.SortOrder
  finalParticipantsIds?: Prisma.SortOrder
  participantsCount?: Prisma.SortOrder
  initialNotes?: Prisma.SortOrder
  finalNotes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PointSessionAvgOrderByAggregateInput = {
  weeklyGoalSecondsSnapshot?: Prisma.SortOrder
  totalSeconds?: Prisma.SortOrder
  participantsCount?: Prisma.SortOrder
}

export type PointSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  weeklyGoalSecondsSnapshot?: Prisma.SortOrder
  voiceChannelId?: Prisma.SortOrder
  activity?: Prisma.SortOrder
  messageOpenLink?: Prisma.SortOrder
  messageCloseLink?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  totalSeconds?: Prisma.SortOrder
  participantsCount?: Prisma.SortOrder
  initialNotes?: Prisma.SortOrder
  finalNotes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PointSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  weeklyGoalSecondsSnapshot?: Prisma.SortOrder
  voiceChannelId?: Prisma.SortOrder
  activity?: Prisma.SortOrder
  messageOpenLink?: Prisma.SortOrder
  messageCloseLink?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  totalSeconds?: Prisma.SortOrder
  participantsCount?: Prisma.SortOrder
  initialNotes?: Prisma.SortOrder
  finalNotes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PointSessionSumOrderByAggregateInput = {
  weeklyGoalSecondsSnapshot?: Prisma.SortOrder
  totalSeconds?: Prisma.SortOrder
  participantsCount?: Prisma.SortOrder
}

export type PointSessionScalarRelationFilter = {
  is?: Prisma.PointSessionWhereInput
  isNot?: Prisma.PointSessionWhereInput
}

export type PointSessionCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.PointSessionCreateWithoutMemberInput, Prisma.PointSessionUncheckedCreateWithoutMemberInput> | Prisma.PointSessionCreateWithoutMemberInput[] | Prisma.PointSessionUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PointSessionCreateOrConnectWithoutMemberInput | Prisma.PointSessionCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.PointSessionCreateManyMemberInputEnvelope
  connect?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
}

export type PointSessionUncheckedCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.PointSessionCreateWithoutMemberInput, Prisma.PointSessionUncheckedCreateWithoutMemberInput> | Prisma.PointSessionCreateWithoutMemberInput[] | Prisma.PointSessionUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PointSessionCreateOrConnectWithoutMemberInput | Prisma.PointSessionCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.PointSessionCreateManyMemberInputEnvelope
  connect?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
}

export type PointSessionUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.PointSessionCreateWithoutMemberInput, Prisma.PointSessionUncheckedCreateWithoutMemberInput> | Prisma.PointSessionCreateWithoutMemberInput[] | Prisma.PointSessionUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PointSessionCreateOrConnectWithoutMemberInput | Prisma.PointSessionCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.PointSessionUpsertWithWhereUniqueWithoutMemberInput | Prisma.PointSessionUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.PointSessionCreateManyMemberInputEnvelope
  set?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
  disconnect?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
  delete?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
  connect?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
  update?: Prisma.PointSessionUpdateWithWhereUniqueWithoutMemberInput | Prisma.PointSessionUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.PointSessionUpdateManyWithWhereWithoutMemberInput | Prisma.PointSessionUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.PointSessionScalarWhereInput | Prisma.PointSessionScalarWhereInput[]
}

export type PointSessionUncheckedUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.PointSessionCreateWithoutMemberInput, Prisma.PointSessionUncheckedCreateWithoutMemberInput> | Prisma.PointSessionCreateWithoutMemberInput[] | Prisma.PointSessionUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PointSessionCreateOrConnectWithoutMemberInput | Prisma.PointSessionCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.PointSessionUpsertWithWhereUniqueWithoutMemberInput | Prisma.PointSessionUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.PointSessionCreateManyMemberInputEnvelope
  set?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
  disconnect?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
  delete?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
  connect?: Prisma.PointSessionWhereUniqueInput | Prisma.PointSessionWhereUniqueInput[]
  update?: Prisma.PointSessionUpdateWithWhereUniqueWithoutMemberInput | Prisma.PointSessionUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.PointSessionUpdateManyWithWhereWithoutMemberInput | Prisma.PointSessionUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.PointSessionScalarWhereInput | Prisma.PointSessionScalarWhereInput[]
}

export type PointSessionCreateinitialParticipantsIdsInput = {
  set: string[]
}

export type PointSessionCreatefinalParticipantsIdsInput = {
  set: string[]
}

export type EnumPointSessionStatusFieldUpdateOperationsInput = {
  set?: $Enums.PointSessionStatus
}

export type PointSessionUpdateinitialParticipantsIdsInput = {
  set?: string[]
  push?: string | string[]
}

export type PointSessionUpdatefinalParticipantsIdsInput = {
  set?: string[]
  push?: string | string[]
}

export type PointSessionCreateNestedOneWithoutPausesInput = {
  create?: Prisma.XOR<Prisma.PointSessionCreateWithoutPausesInput, Prisma.PointSessionUncheckedCreateWithoutPausesInput>
  connectOrCreate?: Prisma.PointSessionCreateOrConnectWithoutPausesInput
  connect?: Prisma.PointSessionWhereUniqueInput
}

export type PointSessionUpdateOneRequiredWithoutPausesNestedInput = {
  create?: Prisma.XOR<Prisma.PointSessionCreateWithoutPausesInput, Prisma.PointSessionUncheckedCreateWithoutPausesInput>
  connectOrCreate?: Prisma.PointSessionCreateOrConnectWithoutPausesInput
  upsert?: Prisma.PointSessionUpsertWithoutPausesInput
  connect?: Prisma.PointSessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PointSessionUpdateToOneWithWhereWithoutPausesInput, Prisma.PointSessionUpdateWithoutPausesInput>, Prisma.PointSessionUncheckedUpdateWithoutPausesInput>
}

export type PointSessionCreateWithoutMemberInput = {
  id?: string
  status?: $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: number | null
  voiceChannelId?: string | null
  activity?: string | null
  messageOpenLink?: string | null
  messageCloseLink?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  totalSeconds?: number | null
  initialParticipantsIds?: Prisma.PointSessionCreateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionCreatefinalParticipantsIdsInput | string[]
  participantsCount?: number | null
  initialNotes?: string | null
  finalNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  pauses?: Prisma.PauseCreateNestedManyWithoutPointSessionInput
}

export type PointSessionUncheckedCreateWithoutMemberInput = {
  id?: string
  status?: $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: number | null
  voiceChannelId?: string | null
  activity?: string | null
  messageOpenLink?: string | null
  messageCloseLink?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  totalSeconds?: number | null
  initialParticipantsIds?: Prisma.PointSessionCreateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionCreatefinalParticipantsIdsInput | string[]
  participantsCount?: number | null
  initialNotes?: string | null
  finalNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  pauses?: Prisma.PauseUncheckedCreateNestedManyWithoutPointSessionInput
}

export type PointSessionCreateOrConnectWithoutMemberInput = {
  where: Prisma.PointSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.PointSessionCreateWithoutMemberInput, Prisma.PointSessionUncheckedCreateWithoutMemberInput>
}

export type PointSessionCreateManyMemberInputEnvelope = {
  data: Prisma.PointSessionCreateManyMemberInput | Prisma.PointSessionCreateManyMemberInput[]
  skipDuplicates?: boolean
}

export type PointSessionUpsertWithWhereUniqueWithoutMemberInput = {
  where: Prisma.PointSessionWhereUniqueInput
  update: Prisma.XOR<Prisma.PointSessionUpdateWithoutMemberInput, Prisma.PointSessionUncheckedUpdateWithoutMemberInput>
  create: Prisma.XOR<Prisma.PointSessionCreateWithoutMemberInput, Prisma.PointSessionUncheckedCreateWithoutMemberInput>
}

export type PointSessionUpdateWithWhereUniqueWithoutMemberInput = {
  where: Prisma.PointSessionWhereUniqueInput
  data: Prisma.XOR<Prisma.PointSessionUpdateWithoutMemberInput, Prisma.PointSessionUncheckedUpdateWithoutMemberInput>
}

export type PointSessionUpdateManyWithWhereWithoutMemberInput = {
  where: Prisma.PointSessionScalarWhereInput
  data: Prisma.XOR<Prisma.PointSessionUpdateManyMutationInput, Prisma.PointSessionUncheckedUpdateManyWithoutMemberInput>
}

export type PointSessionScalarWhereInput = {
  AND?: Prisma.PointSessionScalarWhereInput | Prisma.PointSessionScalarWhereInput[]
  OR?: Prisma.PointSessionScalarWhereInput[]
  NOT?: Prisma.PointSessionScalarWhereInput | Prisma.PointSessionScalarWhereInput[]
  id?: Prisma.StringFilter<"PointSession"> | string
  memberId?: Prisma.StringFilter<"PointSession"> | string
  status?: Prisma.EnumPointSessionStatusFilter<"PointSession"> | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.IntNullableFilter<"PointSession"> | number | null
  voiceChannelId?: Prisma.StringNullableFilter<"PointSession"> | string | null
  activity?: Prisma.StringNullableFilter<"PointSession"> | string | null
  messageOpenLink?: Prisma.StringNullableFilter<"PointSession"> | string | null
  messageCloseLink?: Prisma.StringNullableFilter<"PointSession"> | string | null
  startedAt?: Prisma.DateTimeFilter<"PointSession"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"PointSession"> | Date | string | null
  totalSeconds?: Prisma.IntNullableFilter<"PointSession"> | number | null
  initialParticipantsIds?: Prisma.StringNullableListFilter<"PointSession">
  finalParticipantsIds?: Prisma.StringNullableListFilter<"PointSession">
  participantsCount?: Prisma.IntNullableFilter<"PointSession"> | number | null
  initialNotes?: Prisma.StringNullableFilter<"PointSession"> | string | null
  finalNotes?: Prisma.StringNullableFilter<"PointSession"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PointSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PointSession"> | Date | string
}

export type PointSessionCreateWithoutPausesInput = {
  id?: string
  status?: $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: number | null
  voiceChannelId?: string | null
  activity?: string | null
  messageOpenLink?: string | null
  messageCloseLink?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  totalSeconds?: number | null
  initialParticipantsIds?: Prisma.PointSessionCreateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionCreatefinalParticipantsIdsInput | string[]
  participantsCount?: number | null
  initialNotes?: string | null
  finalNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutPointSessionsInput
}

export type PointSessionUncheckedCreateWithoutPausesInput = {
  id?: string
  memberId: string
  status?: $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: number | null
  voiceChannelId?: string | null
  activity?: string | null
  messageOpenLink?: string | null
  messageCloseLink?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  totalSeconds?: number | null
  initialParticipantsIds?: Prisma.PointSessionCreateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionCreatefinalParticipantsIdsInput | string[]
  participantsCount?: number | null
  initialNotes?: string | null
  finalNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PointSessionCreateOrConnectWithoutPausesInput = {
  where: Prisma.PointSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.PointSessionCreateWithoutPausesInput, Prisma.PointSessionUncheckedCreateWithoutPausesInput>
}

export type PointSessionUpsertWithoutPausesInput = {
  update: Prisma.XOR<Prisma.PointSessionUpdateWithoutPausesInput, Prisma.PointSessionUncheckedUpdateWithoutPausesInput>
  create: Prisma.XOR<Prisma.PointSessionCreateWithoutPausesInput, Prisma.PointSessionUncheckedCreateWithoutPausesInput>
  where?: Prisma.PointSessionWhereInput
}

export type PointSessionUpdateToOneWithWhereWithoutPausesInput = {
  where?: Prisma.PointSessionWhereInput
  data: Prisma.XOR<Prisma.PointSessionUpdateWithoutPausesInput, Prisma.PointSessionUncheckedUpdateWithoutPausesInput>
}

export type PointSessionUpdateWithoutPausesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPointSessionStatusFieldUpdateOperationsInput | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  voiceChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageOpenLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageCloseLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  totalSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialParticipantsIds?: Prisma.PointSessionUpdateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionUpdatefinalParticipantsIdsInput | string[]
  participantsCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  finalNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutPointSessionsNestedInput
}

export type PointSessionUncheckedUpdateWithoutPausesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPointSessionStatusFieldUpdateOperationsInput | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  voiceChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageOpenLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageCloseLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  totalSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialParticipantsIds?: Prisma.PointSessionUpdateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionUpdatefinalParticipantsIdsInput | string[]
  participantsCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  finalNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PointSessionCreateManyMemberInput = {
  id?: string
  status?: $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: number | null
  voiceChannelId?: string | null
  activity?: string | null
  messageOpenLink?: string | null
  messageCloseLink?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  totalSeconds?: number | null
  initialParticipantsIds?: Prisma.PointSessionCreateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionCreatefinalParticipantsIdsInput | string[]
  participantsCount?: number | null
  initialNotes?: string | null
  finalNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PointSessionUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPointSessionStatusFieldUpdateOperationsInput | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  voiceChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageOpenLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageCloseLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  totalSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialParticipantsIds?: Prisma.PointSessionUpdateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionUpdatefinalParticipantsIdsInput | string[]
  participantsCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  finalNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pauses?: Prisma.PauseUpdateManyWithoutPointSessionNestedInput
}

export type PointSessionUncheckedUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPointSessionStatusFieldUpdateOperationsInput | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  voiceChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageOpenLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageCloseLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  totalSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialParticipantsIds?: Prisma.PointSessionUpdateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionUpdatefinalParticipantsIdsInput | string[]
  participantsCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  finalNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pauses?: Prisma.PauseUncheckedUpdateManyWithoutPointSessionNestedInput
}

export type PointSessionUncheckedUpdateManyWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPointSessionStatusFieldUpdateOperationsInput | $Enums.PointSessionStatus
  weeklyGoalSecondsSnapshot?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  voiceChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageOpenLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageCloseLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  totalSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialParticipantsIds?: Prisma.PointSessionUpdateinitialParticipantsIdsInput | string[]
  finalParticipantsIds?: Prisma.PointSessionUpdatefinalParticipantsIdsInput | string[]
  participantsCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  initialNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  finalNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PointSessionCountOutputType
 */

export type PointSessionCountOutputType = {
  pauses: number
}

export type PointSessionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pauses?: boolean | PointSessionCountOutputTypeCountPausesArgs
}

/**
 * PointSessionCountOutputType without action
 */
export type PointSessionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSessionCountOutputType
   */
  select?: Prisma.PointSessionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PointSessionCountOutputType without action
 */
export type PointSessionCountOutputTypeCountPausesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PauseWhereInput
}


export type PointSessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  status?: boolean
  weeklyGoalSecondsSnapshot?: boolean
  voiceChannelId?: boolean
  activity?: boolean
  messageOpenLink?: boolean
  messageCloseLink?: boolean
  startedAt?: boolean
  endedAt?: boolean
  totalSeconds?: boolean
  initialParticipantsIds?: boolean
  finalParticipantsIds?: boolean
  participantsCount?: boolean
  initialNotes?: boolean
  finalNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  pauses?: boolean | Prisma.PointSession$pausesArgs<ExtArgs>
  _count?: boolean | Prisma.PointSessionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pointSession"]>

export type PointSessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  status?: boolean
  weeklyGoalSecondsSnapshot?: boolean
  voiceChannelId?: boolean
  activity?: boolean
  messageOpenLink?: boolean
  messageCloseLink?: boolean
  startedAt?: boolean
  endedAt?: boolean
  totalSeconds?: boolean
  initialParticipantsIds?: boolean
  finalParticipantsIds?: boolean
  participantsCount?: boolean
  initialNotes?: boolean
  finalNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pointSession"]>

export type PointSessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  status?: boolean
  weeklyGoalSecondsSnapshot?: boolean
  voiceChannelId?: boolean
  activity?: boolean
  messageOpenLink?: boolean
  messageCloseLink?: boolean
  startedAt?: boolean
  endedAt?: boolean
  totalSeconds?: boolean
  initialParticipantsIds?: boolean
  finalParticipantsIds?: boolean
  participantsCount?: boolean
  initialNotes?: boolean
  finalNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pointSession"]>

export type PointSessionSelectScalar = {
  id?: boolean
  memberId?: boolean
  status?: boolean
  weeklyGoalSecondsSnapshot?: boolean
  voiceChannelId?: boolean
  activity?: boolean
  messageOpenLink?: boolean
  messageCloseLink?: boolean
  startedAt?: boolean
  endedAt?: boolean
  totalSeconds?: boolean
  initialParticipantsIds?: boolean
  finalParticipantsIds?: boolean
  participantsCount?: boolean
  initialNotes?: boolean
  finalNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PointSessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "memberId" | "status" | "weeklyGoalSecondsSnapshot" | "voiceChannelId" | "activity" | "messageOpenLink" | "messageCloseLink" | "startedAt" | "endedAt" | "totalSeconds" | "initialParticipantsIds" | "finalParticipantsIds" | "participantsCount" | "initialNotes" | "finalNotes" | "createdAt" | "updatedAt", ExtArgs["result"]["pointSession"]>
export type PointSessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  pauses?: boolean | Prisma.PointSession$pausesArgs<ExtArgs>
  _count?: boolean | Prisma.PointSessionCountOutputTypeDefaultArgs<ExtArgs>
}
export type PointSessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}
export type PointSessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}

export type $PointSessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PointSession"
  objects: {
    member: Prisma.$MemberPayload<ExtArgs>
    pauses: Prisma.$PausePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    memberId: string
    status: $Enums.PointSessionStatus
    weeklyGoalSecondsSnapshot: number | null
    voiceChannelId: string | null
    activity: string | null
    messageOpenLink: string | null
    messageCloseLink: string | null
    startedAt: Date
    endedAt: Date | null
    totalSeconds: number | null
    initialParticipantsIds: string[]
    finalParticipantsIds: string[]
    participantsCount: number | null
    initialNotes: string | null
    finalNotes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pointSession"]>
  composites: {}
}

export type PointSessionGetPayload<S extends boolean | null | undefined | PointSessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PointSessionPayload, S>

export type PointSessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PointSessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PointSessionCountAggregateInputType | true
  }

export interface PointSessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PointSession'], meta: { name: 'PointSession' } }
  /**
   * Find zero or one PointSession that matches the filter.
   * @param {PointSessionFindUniqueArgs} args - Arguments to find a PointSession
   * @example
   * // Get one PointSession
   * const pointSession = await prisma.pointSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PointSessionFindUniqueArgs>(args: Prisma.SelectSubset<T, PointSessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PointSessionClient<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PointSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PointSessionFindUniqueOrThrowArgs} args - Arguments to find a PointSession
   * @example
   * // Get one PointSession
   * const pointSession = await prisma.pointSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PointSessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PointSessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PointSessionClient<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PointSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointSessionFindFirstArgs} args - Arguments to find a PointSession
   * @example
   * // Get one PointSession
   * const pointSession = await prisma.pointSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PointSessionFindFirstArgs>(args?: Prisma.SelectSubset<T, PointSessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__PointSessionClient<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PointSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointSessionFindFirstOrThrowArgs} args - Arguments to find a PointSession
   * @example
   * // Get one PointSession
   * const pointSession = await prisma.pointSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PointSessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PointSessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PointSessionClient<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PointSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PointSessions
   * const pointSessions = await prisma.pointSession.findMany()
   * 
   * // Get first 10 PointSessions
   * const pointSessions = await prisma.pointSession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pointSessionWithIdOnly = await prisma.pointSession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PointSessionFindManyArgs>(args?: Prisma.SelectSubset<T, PointSessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PointSession.
   * @param {PointSessionCreateArgs} args - Arguments to create a PointSession.
   * @example
   * // Create one PointSession
   * const PointSession = await prisma.pointSession.create({
   *   data: {
   *     // ... data to create a PointSession
   *   }
   * })
   * 
   */
  create<T extends PointSessionCreateArgs>(args: Prisma.SelectSubset<T, PointSessionCreateArgs<ExtArgs>>): Prisma.Prisma__PointSessionClient<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PointSessions.
   * @param {PointSessionCreateManyArgs} args - Arguments to create many PointSessions.
   * @example
   * // Create many PointSessions
   * const pointSession = await prisma.pointSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PointSessionCreateManyArgs>(args?: Prisma.SelectSubset<T, PointSessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PointSessions and returns the data saved in the database.
   * @param {PointSessionCreateManyAndReturnArgs} args - Arguments to create many PointSessions.
   * @example
   * // Create many PointSessions
   * const pointSession = await prisma.pointSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PointSessions and only return the `id`
   * const pointSessionWithIdOnly = await prisma.pointSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PointSessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PointSessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PointSession.
   * @param {PointSessionDeleteArgs} args - Arguments to delete one PointSession.
   * @example
   * // Delete one PointSession
   * const PointSession = await prisma.pointSession.delete({
   *   where: {
   *     // ... filter to delete one PointSession
   *   }
   * })
   * 
   */
  delete<T extends PointSessionDeleteArgs>(args: Prisma.SelectSubset<T, PointSessionDeleteArgs<ExtArgs>>): Prisma.Prisma__PointSessionClient<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PointSession.
   * @param {PointSessionUpdateArgs} args - Arguments to update one PointSession.
   * @example
   * // Update one PointSession
   * const pointSession = await prisma.pointSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PointSessionUpdateArgs>(args: Prisma.SelectSubset<T, PointSessionUpdateArgs<ExtArgs>>): Prisma.Prisma__PointSessionClient<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PointSessions.
   * @param {PointSessionDeleteManyArgs} args - Arguments to filter PointSessions to delete.
   * @example
   * // Delete a few PointSessions
   * const { count } = await prisma.pointSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PointSessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, PointSessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PointSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PointSessions
   * const pointSession = await prisma.pointSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PointSessionUpdateManyArgs>(args: Prisma.SelectSubset<T, PointSessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PointSessions and returns the data updated in the database.
   * @param {PointSessionUpdateManyAndReturnArgs} args - Arguments to update many PointSessions.
   * @example
   * // Update many PointSessions
   * const pointSession = await prisma.pointSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PointSessions and only return the `id`
   * const pointSessionWithIdOnly = await prisma.pointSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PointSessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PointSessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PointSession.
   * @param {PointSessionUpsertArgs} args - Arguments to update or create a PointSession.
   * @example
   * // Update or create a PointSession
   * const pointSession = await prisma.pointSession.upsert({
   *   create: {
   *     // ... data to create a PointSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PointSession we want to update
   *   }
   * })
   */
  upsert<T extends PointSessionUpsertArgs>(args: Prisma.SelectSubset<T, PointSessionUpsertArgs<ExtArgs>>): Prisma.Prisma__PointSessionClient<runtime.Types.Result.GetResult<Prisma.$PointSessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PointSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointSessionCountArgs} args - Arguments to filter PointSessions to count.
   * @example
   * // Count the number of PointSessions
   * const count = await prisma.pointSession.count({
   *   where: {
   *     // ... the filter for the PointSessions we want to count
   *   }
   * })
  **/
  count<T extends PointSessionCountArgs>(
    args?: Prisma.Subset<T, PointSessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PointSessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PointSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PointSessionAggregateArgs>(args: Prisma.Subset<T, PointSessionAggregateArgs>): Prisma.PrismaPromise<GetPointSessionAggregateType<T>>

  /**
   * Group by PointSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PointSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PointSessionGroupByArgs['orderBy'] }
      : { orderBy?: PointSessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PointSessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPointSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PointSession model
 */
readonly fields: PointSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PointSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PointSessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  member<T extends Prisma.MemberDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MemberDefaultArgs<ExtArgs>>): Prisma.Prisma__MemberClient<runtime.Types.Result.GetResult<Prisma.$MemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  pauses<T extends Prisma.PointSession$pausesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PointSession$pausesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PausePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PointSession model
 */
export interface PointSessionFieldRefs {
  readonly id: Prisma.FieldRef<"PointSession", 'String'>
  readonly memberId: Prisma.FieldRef<"PointSession", 'String'>
  readonly status: Prisma.FieldRef<"PointSession", 'PointSessionStatus'>
  readonly weeklyGoalSecondsSnapshot: Prisma.FieldRef<"PointSession", 'Int'>
  readonly voiceChannelId: Prisma.FieldRef<"PointSession", 'String'>
  readonly activity: Prisma.FieldRef<"PointSession", 'String'>
  readonly messageOpenLink: Prisma.FieldRef<"PointSession", 'String'>
  readonly messageCloseLink: Prisma.FieldRef<"PointSession", 'String'>
  readonly startedAt: Prisma.FieldRef<"PointSession", 'DateTime'>
  readonly endedAt: Prisma.FieldRef<"PointSession", 'DateTime'>
  readonly totalSeconds: Prisma.FieldRef<"PointSession", 'Int'>
  readonly initialParticipantsIds: Prisma.FieldRef<"PointSession", 'String[]'>
  readonly finalParticipantsIds: Prisma.FieldRef<"PointSession", 'String[]'>
  readonly participantsCount: Prisma.FieldRef<"PointSession", 'Int'>
  readonly initialNotes: Prisma.FieldRef<"PointSession", 'String'>
  readonly finalNotes: Prisma.FieldRef<"PointSession", 'String'>
  readonly createdAt: Prisma.FieldRef<"PointSession", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PointSession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PointSession findUnique
 */
export type PointSessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
  /**
   * Filter, which PointSession to fetch.
   */
  where: Prisma.PointSessionWhereUniqueInput
}

/**
 * PointSession findUniqueOrThrow
 */
export type PointSessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
  /**
   * Filter, which PointSession to fetch.
   */
  where: Prisma.PointSessionWhereUniqueInput
}

/**
 * PointSession findFirst
 */
export type PointSessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
  /**
   * Filter, which PointSession to fetch.
   */
  where?: Prisma.PointSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointSessions to fetch.
   */
  orderBy?: Prisma.PointSessionOrderByWithRelationInput | Prisma.PointSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PointSessions.
   */
  cursor?: Prisma.PointSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PointSessions.
   */
  distinct?: Prisma.PointSessionScalarFieldEnum | Prisma.PointSessionScalarFieldEnum[]
}

/**
 * PointSession findFirstOrThrow
 */
export type PointSessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
  /**
   * Filter, which PointSession to fetch.
   */
  where?: Prisma.PointSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointSessions to fetch.
   */
  orderBy?: Prisma.PointSessionOrderByWithRelationInput | Prisma.PointSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PointSessions.
   */
  cursor?: Prisma.PointSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PointSessions.
   */
  distinct?: Prisma.PointSessionScalarFieldEnum | Prisma.PointSessionScalarFieldEnum[]
}

/**
 * PointSession findMany
 */
export type PointSessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
  /**
   * Filter, which PointSessions to fetch.
   */
  where?: Prisma.PointSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointSessions to fetch.
   */
  orderBy?: Prisma.PointSessionOrderByWithRelationInput | Prisma.PointSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PointSessions.
   */
  cursor?: Prisma.PointSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PointSessions.
   */
  distinct?: Prisma.PointSessionScalarFieldEnum | Prisma.PointSessionScalarFieldEnum[]
}

/**
 * PointSession create
 */
export type PointSessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
  /**
   * The data needed to create a PointSession.
   */
  data: Prisma.XOR<Prisma.PointSessionCreateInput, Prisma.PointSessionUncheckedCreateInput>
}

/**
 * PointSession createMany
 */
export type PointSessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PointSessions.
   */
  data: Prisma.PointSessionCreateManyInput | Prisma.PointSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PointSession createManyAndReturn
 */
export type PointSessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * The data used to create many PointSessions.
   */
  data: Prisma.PointSessionCreateManyInput | Prisma.PointSessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PointSession update
 */
export type PointSessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
  /**
   * The data needed to update a PointSession.
   */
  data: Prisma.XOR<Prisma.PointSessionUpdateInput, Prisma.PointSessionUncheckedUpdateInput>
  /**
   * Choose, which PointSession to update.
   */
  where: Prisma.PointSessionWhereUniqueInput
}

/**
 * PointSession updateMany
 */
export type PointSessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PointSessions.
   */
  data: Prisma.XOR<Prisma.PointSessionUpdateManyMutationInput, Prisma.PointSessionUncheckedUpdateManyInput>
  /**
   * Filter which PointSessions to update
   */
  where?: Prisma.PointSessionWhereInput
  /**
   * Limit how many PointSessions to update.
   */
  limit?: number
}

/**
 * PointSession updateManyAndReturn
 */
export type PointSessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * The data used to update PointSessions.
   */
  data: Prisma.XOR<Prisma.PointSessionUpdateManyMutationInput, Prisma.PointSessionUncheckedUpdateManyInput>
  /**
   * Filter which PointSessions to update
   */
  where?: Prisma.PointSessionWhereInput
  /**
   * Limit how many PointSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PointSession upsert
 */
export type PointSessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
  /**
   * The filter to search for the PointSession to update in case it exists.
   */
  where: Prisma.PointSessionWhereUniqueInput
  /**
   * In case the PointSession found by the `where` argument doesn't exist, create a new PointSession with this data.
   */
  create: Prisma.XOR<Prisma.PointSessionCreateInput, Prisma.PointSessionUncheckedCreateInput>
  /**
   * In case the PointSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PointSessionUpdateInput, Prisma.PointSessionUncheckedUpdateInput>
}

/**
 * PointSession delete
 */
export type PointSessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
  /**
   * Filter which PointSession to delete.
   */
  where: Prisma.PointSessionWhereUniqueInput
}

/**
 * PointSession deleteMany
 */
export type PointSessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PointSessions to delete
   */
  where?: Prisma.PointSessionWhereInput
  /**
   * Limit how many PointSessions to delete.
   */
  limit?: number
}

/**
 * PointSession.pauses
 */
export type PointSession$pausesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pause
   */
  select?: Prisma.PauseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pause
   */
  omit?: Prisma.PauseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PauseInclude<ExtArgs> | null
  where?: Prisma.PauseWhereInput
  orderBy?: Prisma.PauseOrderByWithRelationInput | Prisma.PauseOrderByWithRelationInput[]
  cursor?: Prisma.PauseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PauseScalarFieldEnum | Prisma.PauseScalarFieldEnum[]
}

/**
 * PointSession without action
 */
export type PointSessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointSession
   */
  select?: Prisma.PointSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointSession
   */
  omit?: Prisma.PointSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointSessionInclude<ExtArgs> | null
}
