
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Plan
 * 
 */
export type Plan = Prisma.PlanModel
/**
 * Model Guild
 * 
 */
export type Guild = Prisma.GuildModel
/**
 * Model Settings
 * 
 */
export type Settings = Prisma.SettingsModel
/**
 * Model Template
 * 
 */
export type Template = Prisma.TemplateModel
/**
 * Model ServerLink
 * 
 */
export type ServerLink = Prisma.ServerLinkModel
/**
 * Model Audit
 * 
 */
export type Audit = Prisma.AuditModel
/**
 * Model Member
 * 
 */
export type Member = Prisma.MemberModel
/**
 * Model PointSession
 * 
 */
export type PointSession = Prisma.PointSessionModel
/**
 * Model Pause
 * 
 */
export type Pause = Prisma.PauseModel
/**
 * Model MemberFlow
 * 
 */
export type MemberFlow = Prisma.MemberFlowModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Subscription
 * 
 */
export type Subscription = Prisma.SubscriptionModel
