
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Slug = {
  free: 'free',
  andromeda: 'andromeda'
} as const

export type Slug = (typeof Slug)[keyof typeof Slug]


export const Action = {
  update_global_weekly_goal_duration: 'update_global_weekly_goal_duration',
  update_global_weekly_goal_status: 'update_global_weekly_goal_status',
  update_user_weekly_goal_duration: 'update_user_weekly_goal_duration',
  update_user_weekly_goal_status: 'update_user_weekly_goal_status',
  update_point_open_log_channel_id: 'update_point_open_log_channel_id',
  update_point_close_log_channel_id: 'update_point_close_log_channel_id'
} as const

export type Action = (typeof Action)[keyof typeof Action]


export const MemberStatus = {
  active: 'active',
  inactive: 'inactive',
  banned: 'banned',
  out_of_server: 'out_of_server'
} as const

export type MemberStatus = (typeof MemberStatus)[keyof typeof MemberStatus]


export const PointSessionStatus = {
  active: 'active',
  paused: 'paused',
  finished: 'finished',
  cancelled: 'cancelled'
} as const

export type PointSessionStatus = (typeof PointSessionStatus)[keyof typeof PointSessionStatus]


export const PauseStatus = {
  active: 'active',
  finished: 'finished',
  auto_finished: 'auto_finished',
  cancelled: 'cancelled'
} as const

export type PauseStatus = (typeof PauseStatus)[keyof typeof PauseStatus]


export const MemberFlowAction = {
  join: 'join',
  leave: 'leave',
  ban: 'ban'
} as const

export type MemberFlowAction = (typeof MemberFlowAction)[keyof typeof MemberFlowAction]


export const SubscriptionStatus = {
  pending: 'pending',
  authorized: 'authorized',
  paused: 'paused',
  cancelled: 'cancelled'
} as const

export type SubscriptionStatus = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus]
